// Code generated by protoc-gen-psrpc v0.8.0, DO NOT EDIT.
// source: rpc/ingress.proto

package rpc

import (
	"context"

	"github.com/livekit/psrpc"
	"github.com/livekit/psrpc/pkg/client"
	"github.com/livekit/psrpc/pkg/info"
	"github.com/livekit/psrpc/pkg/rand"
	"github.com/livekit/psrpc/pkg/server"
	"github.com/livekit/psrpc/version"
)
import google_protobuf "google.golang.org/protobuf/types/known/emptypb"
import livekit5 "github.com/livekit/protocol/livekit"

var _ = version.PsrpcVersion_0_8

// ================================
// IngressInternal Client Interface
// ================================

type IngressInternalClient interface {
	StartIngress(ctx context.Context, req *StartIngressRequest, opts ...psrpc.RequestOption) (*livekit5.IngressInfo, error)

	ListActiveIngress(ctx context.Context, topic string, req *ListActiveIngressRequest, opts ...psrpc.RequestOption) (<-chan *psrpc.Response[*ListActiveIngressResponse], error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ====================================
// IngressInternal ServerImpl Interface
// ====================================

type IngressInternalServerImpl interface {
	StartIngress(context.Context, *StartIngressRequest) (*livekit5.IngressInfo, error)
	StartIngressAffinity(context.Context, *StartIngressRequest) float32

	ListActiveIngress(context.Context, *ListActiveIngressRequest) (*ListActiveIngressResponse, error)
}

// ================================
// IngressInternal Server Interface
// ================================

type IngressInternalServer interface {
	RegisterListActiveIngressTopic(topic string) error
	DeregisterListActiveIngressTopic(topic string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ======================
// IngressInternal Client
// ======================

type ingressInternalClient struct {
	client *client.RPCClient
}

// NewIngressInternalClient creates a psrpc client that implements the IngressInternalClient interface.
func NewIngressInternalClient(bus psrpc.MessageBus, opts ...psrpc.ClientOption) (IngressInternalClient, error) {
	sd := &info.ServiceDefinition{
		Name: "IngressInternal",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("StartIngress", true, false, true, false)
	sd.RegisterMethod("ListActiveIngress", false, true, false, false)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &ingressInternalClient{
		client: rpcClient,
	}, nil
}

func (c *ingressInternalClient) StartIngress(ctx context.Context, req *StartIngressRequest, opts ...psrpc.RequestOption) (*livekit5.IngressInfo, error) {
	return client.RequestSingle[*livekit5.IngressInfo](ctx, c.client, "StartIngress", nil, req, opts...)
}

func (c *ingressInternalClient) ListActiveIngress(ctx context.Context, topic string, req *ListActiveIngressRequest, opts ...psrpc.RequestOption) (<-chan *psrpc.Response[*ListActiveIngressResponse], error) {
	return client.RequestMulti[*ListActiveIngressResponse](ctx, c.client, "ListActiveIngress", []string{topic}, req, opts...)
}

func (s *ingressInternalClient) Close() {
	s.client.Close()
}

// ======================
// IngressInternal Server
// ======================

type ingressInternalServer struct {
	svc IngressInternalServerImpl
	rpc *server.RPCServer
}

// NewIngressInternalServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewIngressInternalServer(svc IngressInternalServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (IngressInternalServer, error) {
	sd := &info.ServiceDefinition{
		Name: "IngressInternal",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("StartIngress", true, false, true, false)
	var err error
	err = server.RegisterHandler(s, "StartIngress", nil, svc.StartIngress, svc.StartIngressAffinity)
	if err != nil {
		s.Close(false)
		return nil, err
	}

	sd.RegisterMethod("ListActiveIngress", false, true, false, false)
	return &ingressInternalServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *ingressInternalServer) RegisterListActiveIngressTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "ListActiveIngress", []string{topic}, s.svc.ListActiveIngress, nil)
}

func (s *ingressInternalServer) DeregisterListActiveIngressTopic(topic string) {
	s.rpc.DeregisterHandler("ListActiveIngress", []string{topic})
}

func (s *ingressInternalServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *ingressInternalServer) Kill() {
	s.rpc.Close(true)
}

// ====================================
// IngressInternal Unimplemented Server
// ====================================

type UnimplementedIngressInternalServer struct{}

func (UnimplementedIngressInternalServer) StartIngress(context.Context, *StartIngressRequest) (*livekit5.IngressInfo, error) {
	return nil, psrpc.ErrUnimplemented
}
func (UnimplementedIngressInternalServer) StartIngressAffinity(context.Context, *StartIngressRequest) float32 {
	return -1
}

func (UnimplementedIngressInternalServer) ListActiveIngress(context.Context, *ListActiveIngressRequest) (*ListActiveIngressResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

// ===============================
// IngressHandler Client Interface
// ===============================

type IngressHandlerClient interface {
	UpdateIngress(ctx context.Context, topic string, req *livekit5.UpdateIngressRequest, opts ...psrpc.RequestOption) (*livekit5.IngressState, error)

	DeleteIngress(ctx context.Context, topic string, req *livekit5.DeleteIngressRequest, opts ...psrpc.RequestOption) (*livekit5.IngressState, error)

	DeleteWHIPResource(ctx context.Context, topic string, req *DeleteWHIPResourceRequest, opts ...psrpc.RequestOption) (*google_protobuf.Empty, error)

	ICERestartWHIPResource(ctx context.Context, topic string, req *ICERestartWHIPResourceRequest, opts ...psrpc.RequestOption) (*ICERestartWHIPResourceResponse, error)

	WHIPRTCConnectionNotify(ctx context.Context, topic string, req *WHIPRTCConnectionNotifyRequest, opts ...psrpc.RequestOption) (*google_protobuf.Empty, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ===================================
// IngressHandler ServerImpl Interface
// ===================================

type IngressHandlerServerImpl interface {
	UpdateIngress(context.Context, *livekit5.UpdateIngressRequest) (*livekit5.IngressState, error)

	DeleteIngress(context.Context, *livekit5.DeleteIngressRequest) (*livekit5.IngressState, error)

	DeleteWHIPResource(context.Context, *DeleteWHIPResourceRequest) (*google_protobuf.Empty, error)

	ICERestartWHIPResource(context.Context, *ICERestartWHIPResourceRequest) (*ICERestartWHIPResourceResponse, error)

	WHIPRTCConnectionNotify(context.Context, *WHIPRTCConnectionNotifyRequest) (*google_protobuf.Empty, error)
}

// ===============================
// IngressHandler Server Interface
// ===============================

type IngressHandlerServer interface {
	RegisterUpdateIngressTopic(topic string) error
	DeregisterUpdateIngressTopic(topic string)
	RegisterDeleteIngressTopic(topic string) error
	DeregisterDeleteIngressTopic(topic string)
	RegisterDeleteWHIPResourceTopic(topic string) error
	DeregisterDeleteWHIPResourceTopic(topic string)
	RegisterICERestartWHIPResourceTopic(topic string) error
	DeregisterICERestartWHIPResourceTopic(topic string)
	RegisterWHIPRTCConnectionNotifyTopic(topic string) error
	DeregisterWHIPRTCConnectionNotifyTopic(topic string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// =====================
// IngressHandler Client
// =====================

type ingressHandlerClient struct {
	client *client.RPCClient
}

// NewIngressHandlerClient creates a psrpc client that implements the IngressHandlerClient interface.
func NewIngressHandlerClient(bus psrpc.MessageBus, opts ...psrpc.ClientOption) (IngressHandlerClient, error) {
	sd := &info.ServiceDefinition{
		Name: "IngressHandler",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("UpdateIngress", false, false, true, true)
	sd.RegisterMethod("DeleteIngress", false, false, true, true)
	sd.RegisterMethod("DeleteWHIPResource", false, false, true, true)
	sd.RegisterMethod("ICERestartWHIPResource", false, false, true, true)
	sd.RegisterMethod("WHIPRTCConnectionNotify", false, false, false, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &ingressHandlerClient{
		client: rpcClient,
	}, nil
}

func (c *ingressHandlerClient) UpdateIngress(ctx context.Context, topic string, req *livekit5.UpdateIngressRequest, opts ...psrpc.RequestOption) (*livekit5.IngressState, error) {
	return client.RequestSingle[*livekit5.IngressState](ctx, c.client, "UpdateIngress", []string{topic}, req, opts...)
}

func (c *ingressHandlerClient) DeleteIngress(ctx context.Context, topic string, req *livekit5.DeleteIngressRequest, opts ...psrpc.RequestOption) (*livekit5.IngressState, error) {
	return client.RequestSingle[*livekit5.IngressState](ctx, c.client, "DeleteIngress", []string{topic}, req, opts...)
}

func (c *ingressHandlerClient) DeleteWHIPResource(ctx context.Context, topic string, req *DeleteWHIPResourceRequest, opts ...psrpc.RequestOption) (*google_protobuf.Empty, error) {
	return client.RequestSingle[*google_protobuf.Empty](ctx, c.client, "DeleteWHIPResource", []string{topic}, req, opts...)
}

func (c *ingressHandlerClient) ICERestartWHIPResource(ctx context.Context, topic string, req *ICERestartWHIPResourceRequest, opts ...psrpc.RequestOption) (*ICERestartWHIPResourceResponse, error) {
	return client.RequestSingle[*ICERestartWHIPResourceResponse](ctx, c.client, "ICERestartWHIPResource", []string{topic}, req, opts...)
}

func (c *ingressHandlerClient) WHIPRTCConnectionNotify(ctx context.Context, topic string, req *WHIPRTCConnectionNotifyRequest, opts ...psrpc.RequestOption) (*google_protobuf.Empty, error) {
	return client.RequestSingle[*google_protobuf.Empty](ctx, c.client, "WHIPRTCConnectionNotify", []string{topic}, req, opts...)
}

func (s *ingressHandlerClient) Close() {
	s.client.Close()
}

// =====================
// IngressHandler Server
// =====================

type ingressHandlerServer struct {
	svc IngressHandlerServerImpl
	rpc *server.RPCServer
}

// NewIngressHandlerServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewIngressHandlerServer(svc IngressHandlerServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (IngressHandlerServer, error) {
	sd := &info.ServiceDefinition{
		Name: "IngressHandler",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("UpdateIngress", false, false, true, true)
	sd.RegisterMethod("DeleteIngress", false, false, true, true)
	sd.RegisterMethod("DeleteWHIPResource", false, false, true, true)
	sd.RegisterMethod("ICERestartWHIPResource", false, false, true, true)
	sd.RegisterMethod("WHIPRTCConnectionNotify", false, false, false, true)
	return &ingressHandlerServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *ingressHandlerServer) RegisterUpdateIngressTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "UpdateIngress", []string{topic}, s.svc.UpdateIngress, nil)
}

func (s *ingressHandlerServer) DeregisterUpdateIngressTopic(topic string) {
	s.rpc.DeregisterHandler("UpdateIngress", []string{topic})
}

func (s *ingressHandlerServer) RegisterDeleteIngressTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "DeleteIngress", []string{topic}, s.svc.DeleteIngress, nil)
}

func (s *ingressHandlerServer) DeregisterDeleteIngressTopic(topic string) {
	s.rpc.DeregisterHandler("DeleteIngress", []string{topic})
}

func (s *ingressHandlerServer) RegisterDeleteWHIPResourceTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "DeleteWHIPResource", []string{topic}, s.svc.DeleteWHIPResource, nil)
}

func (s *ingressHandlerServer) DeregisterDeleteWHIPResourceTopic(topic string) {
	s.rpc.DeregisterHandler("DeleteWHIPResource", []string{topic})
}

func (s *ingressHandlerServer) RegisterICERestartWHIPResourceTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "ICERestartWHIPResource", []string{topic}, s.svc.ICERestartWHIPResource, nil)
}

func (s *ingressHandlerServer) DeregisterICERestartWHIPResourceTopic(topic string) {
	s.rpc.DeregisterHandler("ICERestartWHIPResource", []string{topic})
}

func (s *ingressHandlerServer) RegisterWHIPRTCConnectionNotifyTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "WHIPRTCConnectionNotify", []string{topic}, s.svc.WHIPRTCConnectionNotify, nil)
}

func (s *ingressHandlerServer) DeregisterWHIPRTCConnectionNotifyTopic(topic string) {
	s.rpc.DeregisterHandler("WHIPRTCConnectionNotify", []string{topic})
}

func (s *ingressHandlerServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *ingressHandlerServer) Kill() {
	s.rpc.Close(true)
}

// ===================================
// IngressHandler Unimplemented Server
// ===================================

type UnimplementedIngressHandlerServer struct{}

func (UnimplementedIngressHandlerServer) UpdateIngress(context.Context, *livekit5.UpdateIngressRequest) (*livekit5.IngressState, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedIngressHandlerServer) DeleteIngress(context.Context, *livekit5.DeleteIngressRequest) (*livekit5.IngressState, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedIngressHandlerServer) DeleteWHIPResource(context.Context, *DeleteWHIPResourceRequest) (*google_protobuf.Empty, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedIngressHandlerServer) ICERestartWHIPResource(context.Context, *ICERestartWHIPResourceRequest) (*ICERestartWHIPResourceResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedIngressHandlerServer) WHIPRTCConnectionNotify(context.Context, *WHIPRTCConnectionNotifyRequest) (*google_protobuf.Empty, error) {
	return nil, psrpc.ErrUnimplemented
}

var psrpcFileDescriptor3 = []byte{
	// 950 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x72, 0xe3, 0x44,
	0x10, 0x2e, 0xd9, 0x8e, 0x93, 0xb4, 0xe3, 0x6c, 0x32, 0xf9, 0x59, 0x45, 0x54, 0x42, 0x50, 0x2e,
	0x29, 0xb6, 0x90, 0x29, 0x53, 0x14, 0x14, 0x07, 0xc8, 0xe6, 0xaf, 0x62, 0x76, 0x17, 0x52, 0x4a,
	0x16, 0xaa, 0x38, 0xa0, 0x52, 0xa4, 0x91, 0x76, 0x88, 0xac, 0x11, 0x33, 0xa3, 0xb8, 0x7c, 0xe3,
	0x9a, 0x3b, 0x2f, 0xc0, 0x2b, 0xe4, 0x18, 0x9e, 0x82, 0xe2, 0x85, 0xa8, 0xf9, 0xb1, 0x63, 0xc7,
	0x76, 0x80, 0xc3, 0xde, 0xd4, 0xdd, 0x5f, 0x7d, 0x3d, 0x33, 0xdd, 0xfd, 0xb5, 0x60, 0x95, 0x15,
	0x51, 0x8b, 0xe4, 0x29, 0xc3, 0x9c, 0x7b, 0x05, 0xa3, 0x82, 0xa2, 0x2a, 0x2b, 0x22, 0xa7, 0x49,
	0x0b, 0x41, 0x68, 0x6e, 0x7c, 0xce, 0x46, 0x46, 0x6e, 0xf0, 0x35, 0x11, 0xc1, 0x18, 0xd4, 0xf9,
	0x20, 0xa5, 0x34, 0xcd, 0x70, 0x4b, 0x59, 0x57, 0x65, 0xd2, 0xc2, 0xdd, 0x42, 0xf4, 0x4d, 0x70,
	0x3d, 0xa3, 0x69, 0x8a, 0x59, 0x6b, 0x8c, 0xc9, 0x75, 0xc0, 0x7e, 0x4d, 0xb8, 0x78, 0x19, 0x09,
	0x72, 0x83, 0x3b, 0x9a, 0xcd, 0xc7, 0xbf, 0x96, 0x98, 0x0b, 0xf7, 0x37, 0x0b, 0xb6, 0xa6, 0x04,
	0x79, 0x41, 0x73, 0x8e, 0xd1, 0x1e, 0x34, 0x4c, 0xf6, 0x80, 0xc4, 0xdc, 0xb6, 0x76, 0xab, 0xfb,
	0x8b, 0x87, 0x15, 0xdb, 0xf2, 0xc1, 0xb8, 0x3b, 0x31, 0x47, 0x5f, 0xc3, 0xca, 0x00, 0xc4, 0x31,
	0xe7, 0x32, 0xb1, 0x5d, 0xd9, 0xad, 0xee, 0x37, 0xda, 0x6b, 0x1e, 0x2b, 0x22, 0xcf, 0x90, 0x5e,
	0xe8, 0x98, 0xff, 0x8c, 0x8c, 0xd9, 0xdc, 0xfd, 0x05, 0xb6, 0x8e, 0x71, 0x86, 0x05, 0xfe, 0xf1,
	0xac, 0x73, 0xee, 0x63, 0x4e, 0x4b, 0x16, 0x61, 0x73, 0x3e, 0xe4, 0x41, 0x83, 0x19, 0x57, 0x40,
	0x62, 0xdb, 0xda, 0xb5, 0xf6, 0x17, 0x0f, 0x9b, 0xf7, 0xe7, 0x30, 0xf0, 0x76, 0x8e, 0xfd, 0x87,
	0xef, 0x18, 0x6d, 0x03, 0x70, 0xc1, 0x70, 0xd8, 0x0d, 0xae, 0x71, 0xdf, 0xae, 0x48, 0xb8, 0xbf,
	0xa8, 0x3d, 0xaf, 0x70, 0xdf, 0xfd, 0xa3, 0x02, 0xdb, 0x9d, 0xa3, 0x13, 0x1f, 0x73, 0x11, 0x32,
	0xf1, 0xfe, 0x13, 0xa2, 0x3d, 0x68, 0x96, 0x1c, 0xb3, 0x20, 0x61, 0x61, 0xda, 0xc5, 0xb9, 0xb0,
	0xab, 0x0a, 0xb1, 0x24, 0x9d, 0xa7, 0xc6, 0x87, 0x1c, 0x58, 0x28, 0x42, 0xce, 0x7b, 0x94, 0xc5,
	0x76, 0x4d, 0xc5, 0x87, 0x36, 0xda, 0x01, 0x88, 0xc2, 0x3c, 0x26, 0x71, 0x28, 0x30, 0xb7, 0xe7,
	0x64, 0x05, 0xfc, 0x11, 0x0f, 0xfa, 0x1c, 0x9e, 0xb3, 0xb0, 0x17, 0x08, 0x46, 0xa2, 0xeb, 0x0c,
	0x07, 0x24, 0xc2, 0x01, 0x8f, 0x0b, 0x99, 0xce, 0xae, 0x2b, 0xaa, 0x75, 0x16, 0xf6, 0x2e, 0x75,
	0xb4, 0x13, 0xe1, 0x0b, 0x1d, 0x43, 0x5b, 0xb0, 0x40, 0x92, 0xa0, 0x1b, 0x8a, 0xe8, 0x9d, 0x3d,
	0xaf, 0x70, 0xf3, 0x24, 0x79, 0x23, 0x4d, 0x37, 0x86, 0x9d, 0x59, 0x4f, 0x64, 0xda, 0xc2, 0x83,
	0xb5, 0x69, 0xf9, 0xd4, 0x5b, 0xf9, 0xab, 0x62, 0x22, 0x19, 0x82, 0x1a, 0x16, 0x61, 0x6a, 0x5e,
	0x47, 0x7d, 0xbb, 0x7f, 0x59, 0xb0, 0xa3, 0xc8, 0x2f, 0x8f, 0x8e, 0x68, 0x9e, 0xe3, 0x48, 0x76,
	0xec, 0x77, 0x54, 0x90, 0xa4, 0x3f, 0x28, 0xc5, 0x17, 0xb0, 0x5c, 0x84, 0x4c, 0x90, 0x88, 0x14,
	0x61, 0x2e, 0x1e, 0xaa, 0xb1, 0x72, 0x7f, 0xde, 0x1c, 0x09, 0x74, 0x8e, 0xfd, 0x31, 0x33, 0x46,
	0x9b, 0x50, 0x8f, 0x32, 0xca, 0x71, 0xac, 0x32, 0x2e, 0xf8, 0xc6, 0x42, 0x1e, 0xcc, 0xdd, 0x90,
	0x18, 0x53, 0x55, 0x84, 0x46, 0xdb, 0xf6, 0xcc, 0x88, 0x79, 0x9d, 0xbc, 0x28, 0xc5, 0x0f, 0x32,
	0x74, 0x21, 0x42, 0x81, 0x7d, 0x0d, 0x93, 0xf8, 0xb0, 0x8c, 0x09, 0xb5, 0x6b, 0xd3, 0xf0, 0x2f,
	0x65, 0xc8, 0xe0, 0x15, 0xcc, 0xfd, 0xbd, 0x0a, 0x6b, 0x17, 0xf2, 0xd5, 0xc6, 0x87, 0x0c, 0xed,
	0x43, 0x8d, 0xe4, 0x09, 0x55, 0xc7, 0x6f, 0xb4, 0xd7, 0x47, 0x68, 0xf4, 0x10, 0xe5, 0x09, 0xf5,
	0x15, 0x02, 0xad, 0xc3, 0x9c, 0xa0, 0xd7, 0x38, 0x37, 0x4f, 0xa5, 0x0d, 0xb4, 0x01, 0xf5, 0x1e,
	0x0f, 0x4a, 0x96, 0x99, 0xee, 0x99, 0xeb, 0xf1, 0xb7, 0x2c, 0x43, 0x3e, 0x2c, 0xcb, 0x79, 0x27,
	0x79, 0x1a, 0x24, 0x04, 0x67, 0x31, 0xb7, 0x6b, 0x6a, 0xec, 0x5e, 0xa8, 0xb1, 0x9b, 0x72, 0x10,
	0xef, 0xb5, 0x86, 0x9f, 0x2a, 0xf4, 0x49, 0x2e, 0x58, 0xdf, 0x6f, 0x66, 0xa3, 0x3e, 0xf4, 0x3d,
	0x34, 0x13, 0x1c, 0x8a, 0x92, 0xe1, 0x20, 0xc9, 0xc2, 0x54, 0x77, 0x5c, 0xa3, 0xfd, 0xf1, 0x4c,
	0xca, 0x53, 0x8d, 0x3e, 0x95, 0x60, 0xcd, 0xb8, 0x94, 0x8c, 0xb8, 0x9c, 0x03, 0x40, 0x93, 0x59,
	0xd1, 0x0a, 0x54, 0xe5, 0xb8, 0xe8, 0x8e, 0x91, 0x9f, 0xf2, 0xe6, 0x37, 0x61, 0x56, 0xe2, 0xc1,
	0xcd, 0x95, 0xf1, 0x55, 0xe5, 0x4b, 0xcb, 0xf9, 0x06, 0x56, 0x27, 0x92, 0xfc, 0x1f, 0x02, 0xb7,
	0x0b, 0xcb, 0xe3, 0x1a, 0x84, 0x5e, 0x00, 0x3c, 0xe8, 0x9a, 0xe9, 0xaa, 0xa5, 0xfb, 0xf3, 0x45,
	0xe3, 0xec, 0x1c, 0xfb, 0xc3, 0xcf, 0xf8, 0xb1, 0x22, 0x54, 0xfe, 0x45, 0x11, 0xdc, 0x6f, 0x61,
	0xeb, 0x15, 0xc9, 0xb2, 0x47, 0xb2, 0x67, 0x5a, 0xe1, 0x13, 0x98, 0x37, 0x22, 0x69, 0xba, 0x61,
	0xaa, 0x46, 0x0e, 0x30, 0xed, 0x3f, 0x2d, 0x78, 0x36, 0xec, 0x12, 0x81, 0x59, 0x1e, 0x66, 0xe8,
	0x0c, 0x96, 0x46, 0x0b, 0x81, 0xec, 0x59, 0xb5, 0x71, 0xa6, 0x76, 0x9a, 0xbb, 0x70, 0x77, 0x6b,
	0xd5, 0x0e, 0xac, 0x4f, 0x2d, 0xf4, 0x33, 0xac, 0x4e, 0x68, 0x3f, 0xda, 0x56, 0x74, 0xb3, 0x16,
	0x86, 0xb3, 0x33, 0x2b, 0xac, 0xb5, 0xc1, 0x85, 0xbb, 0x5b, 0xab, 0xbe, 0x62, 0x1d, 0x54, 0xf6,
	0xad, 0xf6, 0xdf, 0xd5, 0xe1, 0xcb, 0x9f, 0x85, 0x79, 0x9c, 0x61, 0x86, 0xde, 0x40, 0xf3, 0x6d,
	0x21, 0x95, 0xeb, 0x21, 0xdd, 0xe0, 0x8c, 0x63, 0xfe, 0x41, 0xba, 0x8d, 0xc7, 0x57, 0x50, 0x03,
	0xe7, 0xd6, 0xef, 0x6e, 0xad, 0xca, 0x8a, 0x25, 0xe9, 0xf4, 0xee, 0x98, 0xa4, 0x1b, 0xf3, 0xff,
	0x47, 0xba, 0x4b, 0x40, 0x93, 0xab, 0x08, 0xe9, 0x2b, 0xcf, 0xdc, 0x51, 0xce, 0xa6, 0xa7, 0x77,
	0xb2, 0x37, 0xd8, 0xc9, 0xde, 0x89, 0xdc, 0xc9, 0x43, 0x56, 0x02, 0x9b, 0xd3, 0x05, 0x15, 0xb9,
	0xba, 0xf8, 0x4f, 0x2d, 0x24, 0x67, 0xef, 0x49, 0x8c, 0x79, 0xf5, 0x41, 0xaa, 0x2b, 0x78, 0x3e,
	0x43, 0x54, 0x91, 0xe6, 0x79, 0x5a, 0x72, 0x67, 0x5e, 0xc5, 0x54, 0xd5, 0xa9, 0xec, 0x5a, 0x87,
	0x1f, 0xfd, 0xf4, 0x61, 0x4a, 0xc4, 0xbb, 0xf2, 0xca, 0x8b, 0x68, 0xb7, 0x65, 0xde, 0x53, 0xff,
	0x8f, 0x44, 0x34, 0x6b, 0xb1, 0x22, 0xba, 0xaa, 0x2b, 0xeb, 0xb3, 0x7f, 0x06, 0x00, 0x5d, 0x56,
	0xe5, 0xf3, 0xeb, 0x08, 0x00, 0x00,
}
