// Code generated by protoc-gen-psrpc v0.3.0, DO NOT EDIT.
// source: rpc/ingress.proto

package rpc

import (
	"context"

	"github.com/livekit/psrpc"
	"github.com/livekit/psrpc/pkg/client"
	"github.com/livekit/psrpc/pkg/info"
	"github.com/livekit/psrpc/pkg/server"
	"github.com/livekit/psrpc/version"
)
import google_protobuf2 "google.golang.org/protobuf/types/known/emptypb"
import livekit2 "github.com/livekit/protocol/livekit"

var _ = version.PsrpcVersion_0_3_0

// ================================
// IngressInternal Client Interface
// ================================

type IngressInternalClient interface {
	ListActiveIngress(ctx context.Context, req *ListActiveIngressRequest, opts ...psrpc.RequestOption) (<-chan *psrpc.Response[*ListActiveIngressResponse], error)
}

// ====================================
// IngressInternal ServerImpl Interface
// ====================================

type IngressInternalServerImpl interface {
	ListActiveIngress(context.Context, *ListActiveIngressRequest) (*ListActiveIngressResponse, error)
}

// ================================
// IngressInternal Server Interface
// ================================

type IngressInternalServer interface {

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ======================
// IngressInternal Client
// ======================

type ingressInternalClient struct {
	client *client.RPCClient
}

// NewIngressInternalClient creates a psrpc client that implements the IngressInternalClient interface.
func NewIngressInternalClient(clientID string, bus psrpc.MessageBus, opts ...psrpc.ClientOption) (IngressInternalClient, error) {
	sd := &info.ServiceDefinition{
		Name: "IngressInternal",
		ID:   clientID,
	}

	sd.RegisterMethod("ListActiveIngress", false, true, false)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &ingressInternalClient{
		client: rpcClient,
	}, nil
}

func (c *ingressInternalClient) ListActiveIngress(ctx context.Context, req *ListActiveIngressRequest, opts ...psrpc.RequestOption) (<-chan *psrpc.Response[*ListActiveIngressResponse], error) {
	return client.RequestMulti[*ListActiveIngressResponse](ctx, c.client, "ListActiveIngress", nil, req, opts...)
}

// ======================
// IngressInternal Server
// ======================

type ingressInternalServer struct {
	svc IngressInternalServerImpl
	rpc *server.RPCServer
}

// NewIngressInternalServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewIngressInternalServer(serverID string, svc IngressInternalServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (IngressInternalServer, error) {
	sd := &info.ServiceDefinition{
		Name: "IngressInternal",
		ID:   serverID,
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("ListActiveIngress", false, true, false)
	var err error
	err = server.RegisterHandler(s, "ListActiveIngress", nil, svc.ListActiveIngress, nil)
	if err != nil {
		s.Close(false)
		return nil, err
	}

	return &ingressInternalServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *ingressInternalServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *ingressInternalServer) Kill() {
	s.rpc.Close(true)
}

// ===============================
// IngressHandler Client Interface
// ===============================

type IngressHandlerClient interface {
	UpdateIngress(ctx context.Context, topic string, req *livekit2.UpdateIngressRequest, opts ...psrpc.RequestOption) (*livekit2.IngressState, error)

	DeleteIngress(ctx context.Context, topic string, req *livekit2.DeleteIngressRequest, opts ...psrpc.RequestOption) (*livekit2.IngressState, error)

	DeleteWHIPResource(ctx context.Context, topic string, req *DeleteWHIPResourceRequest, opts ...psrpc.RequestOption) (*google_protobuf2.Empty, error)
}

// ===================================
// IngressHandler ServerImpl Interface
// ===================================

type IngressHandlerServerImpl interface {
	UpdateIngress(context.Context, *livekit2.UpdateIngressRequest) (*livekit2.IngressState, error)

	DeleteIngress(context.Context, *livekit2.DeleteIngressRequest) (*livekit2.IngressState, error)

	DeleteWHIPResource(context.Context, *DeleteWHIPResourceRequest) (*google_protobuf2.Empty, error)
}

// ===============================
// IngressHandler Server Interface
// ===============================

type IngressHandlerServer interface {
	RegisterUpdateIngressTopic(topic string) error
	DeregisterUpdateIngressTopic(topic string)
	RegisterDeleteIngressTopic(topic string) error
	DeregisterDeleteIngressTopic(topic string)
	RegisterDeleteWHIPResourceTopic(topic string) error
	DeregisterDeleteWHIPResourceTopic(topic string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// =====================
// IngressHandler Client
// =====================

type ingressHandlerClient struct {
	client *client.RPCClient
}

// NewIngressHandlerClient creates a psrpc client that implements the IngressHandlerClient interface.
func NewIngressHandlerClient(clientID string, bus psrpc.MessageBus, opts ...psrpc.ClientOption) (IngressHandlerClient, error) {
	sd := &info.ServiceDefinition{
		Name: "IngressHandler",
		ID:   clientID,
	}

	sd.RegisterMethod("UpdateIngress", false, false, true)
	sd.RegisterMethod("DeleteIngress", false, false, true)
	sd.RegisterMethod("DeleteWHIPResource", false, false, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &ingressHandlerClient{
		client: rpcClient,
	}, nil
}

func (c *ingressHandlerClient) UpdateIngress(ctx context.Context, topic string, req *livekit2.UpdateIngressRequest, opts ...psrpc.RequestOption) (*livekit2.IngressState, error) {
	return client.RequestSingle[*livekit2.IngressState](ctx, c.client, "UpdateIngress", []string{topic}, req, opts...)
}

func (c *ingressHandlerClient) DeleteIngress(ctx context.Context, topic string, req *livekit2.DeleteIngressRequest, opts ...psrpc.RequestOption) (*livekit2.IngressState, error) {
	return client.RequestSingle[*livekit2.IngressState](ctx, c.client, "DeleteIngress", []string{topic}, req, opts...)
}

func (c *ingressHandlerClient) DeleteWHIPResource(ctx context.Context, topic string, req *DeleteWHIPResourceRequest, opts ...psrpc.RequestOption) (*google_protobuf2.Empty, error) {
	return client.RequestSingle[*google_protobuf2.Empty](ctx, c.client, "DeleteWHIPResource", []string{topic}, req, opts...)
}

// =====================
// IngressHandler Server
// =====================

type ingressHandlerServer struct {
	svc IngressHandlerServerImpl
	rpc *server.RPCServer
}

// NewIngressHandlerServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewIngressHandlerServer(serverID string, svc IngressHandlerServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (IngressHandlerServer, error) {
	sd := &info.ServiceDefinition{
		Name: "IngressHandler",
		ID:   serverID,
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("UpdateIngress", false, false, true)
	sd.RegisterMethod("DeleteIngress", false, false, true)
	sd.RegisterMethod("DeleteWHIPResource", false, false, true)
	return &ingressHandlerServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *ingressHandlerServer) RegisterUpdateIngressTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "UpdateIngress", []string{topic}, s.svc.UpdateIngress, nil)
}

func (s *ingressHandlerServer) DeregisterUpdateIngressTopic(topic string) {
	s.rpc.DeregisterHandler("UpdateIngress", []string{topic})
}

func (s *ingressHandlerServer) RegisterDeleteIngressTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "DeleteIngress", []string{topic}, s.svc.DeleteIngress, nil)
}

func (s *ingressHandlerServer) DeregisterDeleteIngressTopic(topic string) {
	s.rpc.DeregisterHandler("DeleteIngress", []string{topic})
}

func (s *ingressHandlerServer) RegisterDeleteWHIPResourceTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "DeleteWHIPResource", []string{topic}, s.svc.DeleteWHIPResource, nil)
}

func (s *ingressHandlerServer) DeregisterDeleteWHIPResourceTopic(topic string) {
	s.rpc.DeregisterHandler("DeleteWHIPResource", []string{topic})
}

func (s *ingressHandlerServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *ingressHandlerServer) Kill() {
	s.rpc.Close(true)
}

var psrpcFileDescriptor1 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x24, 0x2d, 0x14, 0x5d, 0xa9, 0xd2, 0x85, 0x4a, 0x8c, 0xa8, 0xa5, 0x27, 0x11, 0xd9, 0x40,
	0xbd, 0x7a, 0x51, 0x14, 0x1a, 0x50, 0x90, 0xaa, 0x08, 0xbd, 0x94, 0x74, 0xf3, 0x8c, 0x4b, 0xd3,
	0xec, 0xba, 0xfb, 0x52, 0xf0, 0xee, 0xc5, 0xdf, 0xf1, 0x0b, 0x25, 0xdd, 0x4d, 0xb1, 0xd4, 0x80,
	0xa7, 0x90, 0x99, 0x9d, 0x99, 0xf7, 0x86, 0x47, 0x3a, 0x5a, 0xf1, 0x50, 0xe4, 0xa9, 0x06, 0x63,
	0x98, 0xd2, 0x12, 0x25, 0x6d, 0x6a, 0xc5, 0x83, 0xb6, 0x54, 0x28, 0x64, 0xee, 0xb0, 0xa0, 0x9b,
	0x89, 0x05, 0xcc, 0x04, 0x4e, 0xd6, 0x9e, 0x06, 0x87, 0xa9, 0x94, 0x69, 0x06, 0xe1, 0xf2, 0x6f,
	0x5a, 0xbc, 0x86, 0x30, 0x57, 0xf8, 0x61, 0xc9, 0x7e, 0x40, 0xfc, 0x3b, 0x61, 0xf0, 0x8a, 0xa3,
	0x58, 0x40, 0x64, 0x75, 0x23, 0x78, 0x2f, 0xc0, 0x60, 0xff, 0x92, 0x1c, 0xfc, 0xc1, 0x19, 0x25,
	0x73, 0x03, 0xf4, 0x84, 0xec, 0xb8, 0x98, 0x89, 0x48, 0x8c, 0xef, 0xf5, 0x9a, 0xa7, 0xdb, 0x23,
	0xe2, 0xa0, 0x28, 0x31, 0xa5, 0xfa, 0x06, 0x32, 0x40, 0x78, 0x19, 0x46, 0x0f, 0x23, 0x30, 0xb2,
	0xd0, 0x1c, 0x9c, 0x75, 0xa9, 0xd6, 0x0e, 0x9a, 0x88, 0xc4, 0xf7, 0x7a, 0x5e, 0xa9, 0xae, 0xa0,
	0x28, 0x19, 0xcc, 0xc9, 0x9e, 0x4b, 0x8c, 0x72, 0x04, 0x9d, 0xc7, 0x19, 0x1d, 0x93, 0xce, 0xc6,
	0x38, 0xf4, 0x88, 0x69, 0xc5, 0x59, 0xdd, 0x0a, 0xc1, 0x71, 0x1d, 0x6d, 0xb7, 0xe8, 0xb7, 0xbe,
	0xbf, 0xbc, 0xc6, 0x96, 0x37, 0xf8, 0x6c, 0x90, 0x5d, 0xc7, 0x0d, 0xe3, 0x3c, 0xc9, 0x40, 0xd3,
	0x7b, 0xd2, 0x7e, 0x56, 0x49, 0x8c, 0xbf, 0xa2, 0x5c, 0xbf, 0x6c, 0x0d, 0xaf, 0xa2, 0xba, 0x2b,
	0xda, 0x11, 0x8f, 0x18, 0xa3, 0x4b, 0xf0, 0xbd, 0xd2, 0xce, 0xd6, 0xb1, 0x69, 0xb7, 0x86, 0xff,
	0xd3, 0xee, 0x89, 0xd0, 0xcd, 0x76, 0xa9, 0x5d, 0xb7, 0xb6, 0xf6, 0x60, 0x9f, 0xd9, 0x5b, 0x60,
	0xd5, 0x2d, 0xb0, 0xdb, 0xf2, 0x16, 0x2a, 0xd7, 0xeb, 0xf3, 0xf1, 0x59, 0x2a, 0xf0, 0xad, 0x98,
	0x32, 0x2e, 0xe7, 0xa1, 0x1b, 0x60, 0xf5, 0x55, 0xb3, 0x34, 0x34, 0xa0, 0x17, 0x82, 0x43, 0xa8,
	0x15, 0x9f, 0xb6, 0x96, 0x2e, 0x17, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x97, 0xf5, 0xcc,
	0x9f, 0x02, 0x00, 0x00,
}
