// Code generated by protoc-gen-psrpc v0.6.0, DO NOT EDIT.
// source: rpc/signalv2.proto

package rpc

import (
	"context"

	"github.com/livekit/psrpc"
	"github.com/livekit/psrpc/pkg/client"
	"github.com/livekit/psrpc/pkg/info"
	"github.com/livekit/psrpc/pkg/rand"
	"github.com/livekit/psrpc/pkg/server"
	"github.com/livekit/psrpc/version"
)

var _ = version.PsrpcVersion_0_6

// =========================
// Signalv2 Client Interface
// =========================

type Signalv2Client[NodeIdTopicType ~string] interface {
	RelaySignalv2Connect(ctx context.Context, nodeId NodeIdTopicType, req *RelaySignalv2ConnectRequest, opts ...psrpc.RequestOption) (*RelaySignalv2ConnectResponse, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// =============================
// Signalv2 ServerImpl Interface
// =============================

type Signalv2ServerImpl interface {
	RelaySignalv2Connect(context.Context, *RelaySignalv2ConnectRequest) (*RelaySignalv2ConnectResponse, error)
}

// =========================
// Signalv2 Server Interface
// =========================

type Signalv2Server[NodeIdTopicType ~string] interface {
	RegisterRelaySignalv2ConnectTopic(nodeId NodeIdTopicType) error
	DeregisterRelaySignalv2ConnectTopic(nodeId NodeIdTopicType)
	RegisterAllNodeTopics(nodeId NodeIdTopicType) error
	DeregisterAllNodeTopics(nodeId NodeIdTopicType)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ===============
// Signalv2 Client
// ===============

type signalv2Client[NodeIdTopicType ~string] struct {
	client *client.RPCClient
}

// NewSignalv2Client creates a psrpc client that implements the Signalv2Client interface.
func NewSignalv2Client[NodeIdTopicType ~string](bus psrpc.MessageBus, opts ...psrpc.ClientOption) (Signalv2Client[NodeIdTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "Signalv2",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("RelaySignalv2Connect", false, false, false, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &signalv2Client[NodeIdTopicType]{
		client: rpcClient,
	}, nil
}

func (c *signalv2Client[NodeIdTopicType]) RelaySignalv2Connect(ctx context.Context, nodeId NodeIdTopicType, req *RelaySignalv2ConnectRequest, opts ...psrpc.RequestOption) (*RelaySignalv2ConnectResponse, error) {
	return client.RequestSingle[*RelaySignalv2ConnectResponse](ctx, c.client, "RelaySignalv2Connect", []string{string(nodeId)}, req, opts...)
}

func (s *signalv2Client[NodeIdTopicType]) Close() {
	s.client.Close()
}

// ===============
// Signalv2 Server
// ===============

type signalv2Server[NodeIdTopicType ~string] struct {
	svc Signalv2ServerImpl
	rpc *server.RPCServer
}

// NewSignalv2Server builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewSignalv2Server[NodeIdTopicType ~string](svc Signalv2ServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (Signalv2Server[NodeIdTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "Signalv2",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("RelaySignalv2Connect", false, false, false, true)
	return &signalv2Server[NodeIdTopicType]{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *signalv2Server[NodeIdTopicType]) RegisterRelaySignalv2ConnectTopic(nodeId NodeIdTopicType) error {
	return server.RegisterHandler(s.rpc, "RelaySignalv2Connect", []string{string(nodeId)}, s.svc.RelaySignalv2Connect, nil)
}

func (s *signalv2Server[NodeIdTopicType]) DeregisterRelaySignalv2ConnectTopic(nodeId NodeIdTopicType) {
	s.rpc.DeregisterHandler("RelaySignalv2Connect", []string{string(nodeId)})
}

func (s *signalv2Server[NodeIdTopicType]) allNodeTopicRegisterers() server.RegistererSlice {
	return server.RegistererSlice{
		server.NewRegisterer(s.RegisterRelaySignalv2ConnectTopic, s.DeregisterRelaySignalv2ConnectTopic),
	}
}

func (s *signalv2Server[NodeIdTopicType]) RegisterAllNodeTopics(nodeId NodeIdTopicType) error {
	return s.allNodeTopicRegisterers().Register(nodeId)
}

func (s *signalv2Server[NodeIdTopicType]) DeregisterAllNodeTopics(nodeId NodeIdTopicType) {
	s.allNodeTopicRegisterers().Deregister(nodeId)
}

func (s *signalv2Server[NodeIdTopicType]) Shutdown() {
	s.rpc.Close(false)
}

func (s *signalv2Server[NodeIdTopicType]) Kill() {
	s.rpc.Close(true)
}

var psrpcFileDescriptor10 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0xe5, 0xaf, 0x9f, 0xf8, 0x39, 0x11, 0xb4, 0x32, 0x95, 0x1a, 0xa5, 0x48, 0xfd, 0x99,
	0x3a, 0x25, 0x52, 0x18, 0x59, 0x10, 0xdd, 0x18, 0xcd, 0xc6, 0x12, 0xa5, 0xa7, 0x56, 0x09, 0xa4,
	0x3e, 0xc6, 0x76, 0x2b, 0xd8, 0x59, 0xb8, 0x1d, 0x76, 0xee, 0x0d, 0x35, 0x4e, 0x5b, 0x45, 0x54,
	0x5d, 0x22, 0x9d, 0xe7, 0x24, 0xef, 0xf3, 0xc6, 0x06, 0x6e, 0x34, 0x26, 0xb6, 0x58, 0xa8, 0xbc,
	0x5c, 0xa7, 0xb1, 0x36, 0xe4, 0x88, 0xb7, 0x8c, 0xc6, 0xe8, 0x82, 0xb4, 0x2b, 0x48, 0x59, 0xcf,
	0x22, 0x5e, 0x16, 0x6b, 0xf9, 0x5a, 0xb8, 0xcc, 0x10, 0x2d, 0x6b, 0xd6, 0xdd, 0x31, 0x87, 0xd9,
	0xf6, 0xeb, 0xf1, 0x0f, 0x83, 0xbe, 0x90, 0x65, 0xfe, 0xf1, 0x58, 0xa7, 0x4e, 0x49, 0x29, 0x89,
	0x4e, 0xc8, 0xb7, 0x95, 0xb4, 0x8e, 0x0f, 0x20, 0x58, 0x98, 0x5c, 0x39, 0x9b, 0xbd, 0x58, 0x52,
	0x21, 0x1b, 0xb2, 0xc9, 0xb9, 0x00, 0x8f, 0x1e, 0x2c, 0x29, 0x7e, 0x0b, 0x01, 0x1a, 0x99, 0x3b,
	0x59, 0xb9, 0xc2, 0x7f, 0x43, 0x36, 0x09, 0xd2, 0x28, 0xae, 0x65, 0xf1, 0xb4, 0xda, 0x09, 0xa2,
	0x65, 0x9d, 0x28, 0x00, 0x77, 0x88, 0xdf, 0x41, 0x1b, 0xbd, 0x2f, 0x33, 0x7e, 0x1d, 0xb6, 0xaa,
	0x80, 0xde, 0x3e, 0xa0, 0xd1, 0x47, 0x5c, 0x62, 0x63, 0x1e, 0x23, 0x5c, 0x1f, 0xae, 0x6f, 0x35,
	0x29, 0x2b, 0xf9, 0x14, 0x3a, 0x7b, 0x83, 0x67, 0xd5, 0x4f, 0x04, 0x69, 0xf8, 0x57, 0xe1, 0xf7,
	0xa2, 0x8d, 0x4d, 0x90, 0x7e, 0x32, 0x38, 0xdb, 0x0a, 0xf8, 0x3b, 0x74, 0x0f, 0x19, 0xf9, 0x30,
	0x36, 0x1a, 0xe3, 0x23, 0x67, 0x19, 0x8d, 0x8e, 0xbc, 0xe1, 0x4d, 0xe3, 0xfe, 0xf7, 0x17, 0xeb,
	0x75, 0x58, 0x74, 0x05, 0xff, 0x15, 0xcd, 0x25, 0x3f, 0xdd, 0x3c, 0xb3, 0x62, 0xbe, 0xe9, 0x7c,
	0x3f, 0x7a, 0x1a, 0x2c, 0x0a, 0xf7, 0xbc, 0x9a, 0xc5, 0x48, 0xcb, 0xa4, 0x6e, 0x9f, 0x54, 0xf7,
	0x88, 0x54, 0x26, 0x46, 0xe3, 0xec, 0xa4, 0x9a, 0x6e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0xc1, 0x50, 0x5d, 0x29, 0x02, 0x00, 0x00,
}
