// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: livekit_agent_dispatch.proto

package livekit

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ==============================
// AgentDispatchService Interface
// ==============================

type AgentDispatchService interface {
	CreateDispatch(context.Context, *CreateAgentDispatchRequest) (*AgentDispatch, error)

	DeleteDispatch(context.Context, *DeleteAgentDispatchRequest) (*AgentDispatch, error)

	ListDispatch(context.Context, *ListAgentDispatchRequest) (*ListAgentDispatchResponse, error)
}

// ====================================
// AgentDispatchService Protobuf Client
// ====================================

type agentDispatchServiceProtobufClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAgentDispatchServiceProtobufClient creates a Protobuf client that implements the AgentDispatchService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewAgentDispatchServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) AgentDispatchService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "livekit", "AgentDispatchService")
	urls := [3]string{
		serviceURL + "CreateDispatch",
		serviceURL + "DeleteDispatch",
		serviceURL + "ListDispatch",
	}

	return &agentDispatchServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *agentDispatchServiceProtobufClient) CreateDispatch(ctx context.Context, in *CreateAgentDispatchRequest) (*AgentDispatch, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentDispatchService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateDispatch")
	caller := c.callCreateDispatch
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateAgentDispatchRequest) (*AgentDispatch, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateAgentDispatchRequest) when calling interceptor")
					}
					return c.callCreateDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AgentDispatch)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AgentDispatch) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentDispatchServiceProtobufClient) callCreateDispatch(ctx context.Context, in *CreateAgentDispatchRequest) (*AgentDispatch, error) {
	out := new(AgentDispatch)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentDispatchServiceProtobufClient) DeleteDispatch(ctx context.Context, in *DeleteAgentDispatchRequest) (*AgentDispatch, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentDispatchService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteDispatch")
	caller := c.callDeleteDispatch
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteAgentDispatchRequest) (*AgentDispatch, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteAgentDispatchRequest) when calling interceptor")
					}
					return c.callDeleteDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AgentDispatch)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AgentDispatch) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentDispatchServiceProtobufClient) callDeleteDispatch(ctx context.Context, in *DeleteAgentDispatchRequest) (*AgentDispatch, error) {
	out := new(AgentDispatch)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentDispatchServiceProtobufClient) ListDispatch(ctx context.Context, in *ListAgentDispatchRequest) (*ListAgentDispatchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentDispatchService")
	ctx = ctxsetters.WithMethodName(ctx, "ListDispatch")
	caller := c.callListDispatch
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListAgentDispatchRequest) (*ListAgentDispatchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListAgentDispatchRequest) when calling interceptor")
					}
					return c.callListDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListAgentDispatchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListAgentDispatchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentDispatchServiceProtobufClient) callListDispatch(ctx context.Context, in *ListAgentDispatchRequest) (*ListAgentDispatchResponse, error) {
	out := new(ListAgentDispatchResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ================================
// AgentDispatchService JSON Client
// ================================

type agentDispatchServiceJSONClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAgentDispatchServiceJSONClient creates a JSON client that implements the AgentDispatchService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewAgentDispatchServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) AgentDispatchService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "livekit", "AgentDispatchService")
	urls := [3]string{
		serviceURL + "CreateDispatch",
		serviceURL + "DeleteDispatch",
		serviceURL + "ListDispatch",
	}

	return &agentDispatchServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *agentDispatchServiceJSONClient) CreateDispatch(ctx context.Context, in *CreateAgentDispatchRequest) (*AgentDispatch, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentDispatchService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateDispatch")
	caller := c.callCreateDispatch
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateAgentDispatchRequest) (*AgentDispatch, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateAgentDispatchRequest) when calling interceptor")
					}
					return c.callCreateDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AgentDispatch)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AgentDispatch) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentDispatchServiceJSONClient) callCreateDispatch(ctx context.Context, in *CreateAgentDispatchRequest) (*AgentDispatch, error) {
	out := new(AgentDispatch)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentDispatchServiceJSONClient) DeleteDispatch(ctx context.Context, in *DeleteAgentDispatchRequest) (*AgentDispatch, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentDispatchService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteDispatch")
	caller := c.callDeleteDispatch
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteAgentDispatchRequest) (*AgentDispatch, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteAgentDispatchRequest) when calling interceptor")
					}
					return c.callDeleteDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AgentDispatch)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AgentDispatch) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentDispatchServiceJSONClient) callDeleteDispatch(ctx context.Context, in *DeleteAgentDispatchRequest) (*AgentDispatch, error) {
	out := new(AgentDispatch)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentDispatchServiceJSONClient) ListDispatch(ctx context.Context, in *ListAgentDispatchRequest) (*ListAgentDispatchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentDispatchService")
	ctx = ctxsetters.WithMethodName(ctx, "ListDispatch")
	caller := c.callListDispatch
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListAgentDispatchRequest) (*ListAgentDispatchResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListAgentDispatchRequest) when calling interceptor")
					}
					return c.callListDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListAgentDispatchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListAgentDispatchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentDispatchServiceJSONClient) callListDispatch(ctx context.Context, in *ListAgentDispatchRequest) (*ListAgentDispatchResponse, error) {
	out := new(ListAgentDispatchResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===================================
// AgentDispatchService Server Handler
// ===================================

type agentDispatchServiceServer struct {
	AgentDispatchService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewAgentDispatchServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewAgentDispatchServiceServer(svc AgentDispatchService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &agentDispatchServiceServer{
		AgentDispatchService: svc,
		hooks:                serverOpts.Hooks,
		interceptor:          twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:           pathPrefix,
		jsonSkipDefaults:     jsonSkipDefaults,
		jsonCamelCase:        jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *agentDispatchServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *agentDispatchServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// AgentDispatchServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const AgentDispatchServicePathPrefix = "/twirp/livekit.AgentDispatchService/"

func (s *agentDispatchServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentDispatchService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "livekit.AgentDispatchService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "CreateDispatch":
		s.serveCreateDispatch(ctx, resp, req)
		return
	case "DeleteDispatch":
		s.serveDeleteDispatch(ctx, resp, req)
		return
	case "ListDispatch":
		s.serveListDispatch(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *agentDispatchServiceServer) serveCreateDispatch(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreateDispatchJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreateDispatchProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *agentDispatchServiceServer) serveCreateDispatchJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateDispatch")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreateAgentDispatchRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AgentDispatchService.CreateDispatch
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateAgentDispatchRequest) (*AgentDispatch, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateAgentDispatchRequest) when calling interceptor")
					}
					return s.AgentDispatchService.CreateDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AgentDispatch)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AgentDispatch) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AgentDispatch
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AgentDispatch and nil error while calling CreateDispatch. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentDispatchServiceServer) serveCreateDispatchProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateDispatch")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreateAgentDispatchRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AgentDispatchService.CreateDispatch
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateAgentDispatchRequest) (*AgentDispatch, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateAgentDispatchRequest) when calling interceptor")
					}
					return s.AgentDispatchService.CreateDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AgentDispatch)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AgentDispatch) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AgentDispatch
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AgentDispatch and nil error while calling CreateDispatch. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentDispatchServiceServer) serveDeleteDispatch(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteDispatchJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteDispatchProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *agentDispatchServiceServer) serveDeleteDispatchJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteDispatch")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeleteAgentDispatchRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AgentDispatchService.DeleteDispatch
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteAgentDispatchRequest) (*AgentDispatch, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteAgentDispatchRequest) when calling interceptor")
					}
					return s.AgentDispatchService.DeleteDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AgentDispatch)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AgentDispatch) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AgentDispatch
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AgentDispatch and nil error while calling DeleteDispatch. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentDispatchServiceServer) serveDeleteDispatchProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteDispatch")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeleteAgentDispatchRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AgentDispatchService.DeleteDispatch
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteAgentDispatchRequest) (*AgentDispatch, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteAgentDispatchRequest) when calling interceptor")
					}
					return s.AgentDispatchService.DeleteDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AgentDispatch)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AgentDispatch) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AgentDispatch
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AgentDispatch and nil error while calling DeleteDispatch. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentDispatchServiceServer) serveListDispatch(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListDispatchJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListDispatchProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *agentDispatchServiceServer) serveListDispatchJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListDispatch")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListAgentDispatchRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AgentDispatchService.ListDispatch
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListAgentDispatchRequest) (*ListAgentDispatchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListAgentDispatchRequest) when calling interceptor")
					}
					return s.AgentDispatchService.ListDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListAgentDispatchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListAgentDispatchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListAgentDispatchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListAgentDispatchResponse and nil error while calling ListDispatch. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentDispatchServiceServer) serveListDispatchProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListDispatch")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListAgentDispatchRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AgentDispatchService.ListDispatch
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListAgentDispatchRequest) (*ListAgentDispatchResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListAgentDispatchRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListAgentDispatchRequest) when calling interceptor")
					}
					return s.AgentDispatchService.ListDispatch(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListAgentDispatchResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListAgentDispatchResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListAgentDispatchResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListAgentDispatchResponse and nil error while calling ListDispatch. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentDispatchServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *agentDispatchServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *agentDispatchServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "livekit", "AgentDispatchService")
}

var twirpFileDescriptor1 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x76, 0x5a, 0xc8, 0xa4, 0x31, 0x61, 0xa9, 0x90, 0x6b, 0x40, 0x84, 0xf4, 0x12, 0x71,
	0x70, 0x44, 0x10, 0x97, 0x9e, 0x48, 0x48, 0x2a, 0xb5, 0x84, 0x10, 0x2d, 0x2a, 0x07, 0x0e, 0x98,
	0x8d, 0x3d, 0x4a, 0x17, 0xe2, 0x6c, 0xb0, 0xb7, 0x91, 0xf8, 0x06, 0xce, 0xfc, 0x03, 0xe2, 0xc8,
	0x91, 0x2f, 0x42, 0x7c, 0x05, 0xf2, 0xda, 0x31, 0x71, 0xb1, 0x81, 0x1e, 0x7a, 0xf3, 0xbe, 0x79,
	0xfb, 0xfc, 0x34, 0xf3, 0x66, 0xe1, 0xce, 0x9c, 0xaf, 0xf0, 0x3d, 0x97, 0x2e, 0x9b, 0xe1, 0x42,
	0xba, 0x3e, 0x8f, 0x96, 0x4c, 0x7a, 0xa7, 0xce, 0x32, 0x14, 0x52, 0x90, 0xab, 0x69, 0xd5, 0xbe,
	0x99, 0xa3, 0x25, 0x55, 0x7b, 0x77, 0x2e, 0x66, 0x33, 0x0c, 0x3b, 0x62, 0x29, 0xb9, 0x58, 0x44,
	0x09, 0xda, 0xfa, 0xa6, 0x81, 0xfd, 0x34, 0x44, 0x26, 0xb1, 0x17, 0x73, 0x07, 0xa9, 0x22, 0xc5,
	0x0f, 0x67, 0x18, 0x49, 0x72, 0x17, 0x20, 0xf9, 0xd5, 0x82, 0x05, 0x68, 0x69, 0x4d, 0xad, 0x5d,
	0xa5, 0x55, 0x85, 0x8c, 0x59, 0x80, 0x84, 0x40, 0x25, 0x14, 0x22, 0xb0, 0x74, 0x55, 0x50, 0xdf,
	0xe4, 0x1e, 0x5c, 0x0b, 0x50, 0x32, 0x9f, 0x49, 0x66, 0x19, 0x31, 0xde, 0x37, 0xbe, 0x4c, 0x34,
	0x9a, 0x81, 0xe4, 0x09, 0x98, 0x21, 0x46, 0x92, 0x85, 0xd2, 0x5d, 0x8a, 0x39, 0xf7, 0x3e, 0x5a,
	0x95, 0xa6, 0xd6, 0x36, 0xbb, 0x7b, 0x4e, 0x6a, 0xdb, 0x39, 0x16, 0x53, 0x9a, 0x30, 0x26, 0x8a,
	0x40, 0xeb, 0xe1, 0xe6, 0xb1, 0xf5, 0x59, 0x83, 0x1b, 0x54, 0x88, 0x20, 0x67, 0xf9, 0x5f, 0x5e,
	0x37, 0x7d, 0xe9, 0xff, 0xe7, 0xcb, 0xb8, 0xa0, 0xaf, 0xb7, 0x60, 0x0f, 0x70, 0x8e, 0x25, 0xbd,
	0x74, 0xa0, 0xb6, 0x1e, 0x98, 0xcb, 0xfd, 0xc4, 0x60, 0xbf, 0xfe, 0x7d, 0x02, 0x6b, 0xf4, 0x68,
	0x40, 0x7f, 0x7f, 0xfb, 0x45, 0xcd, 0x6d, 0xbd, 0x01, 0x6b, 0xc4, 0x23, 0x79, 0x89, 0xfa, 0x7b,
	0x05, 0xfa, 0xd1, 0x52, 0x2c, 0x22, 0x24, 0x3d, 0x68, 0xe4, 0x73, 0x87, 0x91, 0xa5, 0x35, 0x8d,
	0x76, 0xad, 0x7b, 0x2b, 0x6b, 0x51, 0xfe, 0xe6, 0x75, 0xb6, 0x79, 0xc4, 0xa8, 0xf5, 0x43, 0x83,
	0x7a, 0x7e, 0x6a, 0x26, 0xe8, 0x6b, 0xb3, 0x54, 0xe7, 0xfe, 0xb9, 0x29, 0xea, 0x65, 0x89, 0x33,
	0x4a, 0x12, 0x57, 0x29, 0x9a, 0xec, 0x43, 0xd8, 0x8a, 0x24, 0x93, 0x68, 0x6d, 0x35, 0xb5, 0x76,
	0xad, 0x7b, 0xbb, 0xd8, 0xed, 0xcb, 0x98, 0x42, 0x13, 0x66, 0x41, 0x18, 0xb6, 0x2f, 0x18, 0x06,
	0x09, 0xe4, 0x4f, 0x79, 0xd2, 0x84, 0xca, 0x3b, 0x31, 0x5d, 0xf7, 0x6d, 0x27, 0xa7, 0xa6, 0x2a,
	0x71, 0x03, 0x3c, 0xb5, 0x90, 0xbe, 0xcb, 0xa4, 0x6a, 0x80, 0x41, 0xab, 0x29, 0xd2, 0x53, 0x1b,
	0xe9, 0xab, 0x8c, 0xa9, 0xb2, 0x91, 0x94, 0x53, 0xa4, 0x27, 0x1f, 0x3c, 0x86, 0xc6, 0x79, 0x63,
	0x84, 0x80, 0x79, 0x4c, 0x27, 0xee, 0x8b, 0xb1, 0x7b, 0xd8, 0x3b, 0x1a, 0x9d, 0xd0, 0x61, 0xe3,
	0x0a, 0xa9, 0x43, 0x35, 0xc6, 0xc6, 0xc3, 0x57, 0x43, 0xda, 0xd0, 0xba, 0x9f, 0x74, 0xd8, 0xcd,
	0xbb, 0xc5, 0x70, 0xc5, 0x3d, 0x24, 0xcf, 0xc1, 0x4c, 0x9e, 0x87, 0x6c, 0x60, 0xfb, 0x99, 0xe7,
	0xf2, 0x77, 0xc3, 0x2e, 0x09, 0x44, 0x2c, 0x97, 0x6c, 0x48, 0x81, 0x5c, 0xf9, 0xea, 0x94, 0xca,
	0x9d, 0xc0, 0x4e, 0x1c, 0xd7, 0xec, 0x7c, 0x3f, 0xe3, 0x95, 0x6d, 0x89, 0xdd, 0xfa, 0x1b, 0x25,
	0x09, 0x7a, 0xff, 0xf0, 0xf5, 0xfe, 0x8c, 0xcb, 0xd3, 0xb3, 0xa9, 0xe3, 0x89, 0xa0, 0x93, 0xf2,
	0x3b, 0xea, 0xc1, 0xf4, 0xc4, 0x7c, 0x0d, 0x7c, 0xd5, 0xeb, 0x23, 0xbe, 0xc2, 0x67, 0x5c, 0x3a,
	0x93, 0xb8, 0xf4, 0x53, 0x37, 0xd3, 0xf3, 0xc1, 0x81, 0x02, 0xa6, 0xdb, 0xea, 0xca, 0xa3, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x71, 0x80, 0x1d, 0xb0, 0xb7, 0x05, 0x00, 0x00,
}
