// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: livekit_agent_simulation.proto

package livekit

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// =========================
// AgentSimulation Interface
// =========================

type AgentSimulation interface {
	CreateSimulationRun(context.Context, *CreateSimulationRunRequest) (*CreateSimulationRunResponse, error)

	GetSimulationRun(context.Context, *GetSimulationRunRequest) (*GetSimulationRunResponse, error)

	ListSimulationRuns(context.Context, *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error)
}

// ===============================
// AgentSimulation Protobuf Client
// ===============================

type agentSimulationProtobufClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAgentSimulationProtobufClient creates a Protobuf client that implements the AgentSimulation interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewAgentSimulationProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) AgentSimulation {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "livekit", "AgentSimulation")
	urls := [3]string{
		serviceURL + "CreateSimulationRun",
		serviceURL + "GetSimulationRun",
		serviceURL + "ListSimulationRuns",
	}

	return &agentSimulationProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *agentSimulationProtobufClient) CreateSimulationRun(ctx context.Context, in *CreateSimulationRunRequest) (*CreateSimulationRunResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentSimulation")
	ctx = ctxsetters.WithMethodName(ctx, "CreateSimulationRun")
	caller := c.callCreateSimulationRun
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateSimulationRunRequest) (*CreateSimulationRunResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateSimulationRunRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateSimulationRunRequest) when calling interceptor")
					}
					return c.callCreateSimulationRun(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateSimulationRunResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateSimulationRunResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentSimulationProtobufClient) callCreateSimulationRun(ctx context.Context, in *CreateSimulationRunRequest) (*CreateSimulationRunResponse, error) {
	out := new(CreateSimulationRunResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentSimulationProtobufClient) GetSimulationRun(ctx context.Context, in *GetSimulationRunRequest) (*GetSimulationRunResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentSimulation")
	ctx = ctxsetters.WithMethodName(ctx, "GetSimulationRun")
	caller := c.callGetSimulationRun
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetSimulationRunRequest) (*GetSimulationRunResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSimulationRunRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSimulationRunRequest) when calling interceptor")
					}
					return c.callGetSimulationRun(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSimulationRunResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSimulationRunResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentSimulationProtobufClient) callGetSimulationRun(ctx context.Context, in *GetSimulationRunRequest) (*GetSimulationRunResponse, error) {
	out := new(GetSimulationRunResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentSimulationProtobufClient) ListSimulationRuns(ctx context.Context, in *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentSimulation")
	ctx = ctxsetters.WithMethodName(ctx, "ListSimulationRuns")
	caller := c.callListSimulationRuns
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListSimulationRunsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListSimulationRunsRequest) when calling interceptor")
					}
					return c.callListSimulationRuns(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListSimulationRunsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListSimulationRunsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentSimulationProtobufClient) callListSimulationRuns(ctx context.Context, in *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error) {
	out := new(ListSimulationRunsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// AgentSimulation JSON Client
// ===========================

type agentSimulationJSONClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAgentSimulationJSONClient creates a JSON client that implements the AgentSimulation interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewAgentSimulationJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) AgentSimulation {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "livekit", "AgentSimulation")
	urls := [3]string{
		serviceURL + "CreateSimulationRun",
		serviceURL + "GetSimulationRun",
		serviceURL + "ListSimulationRuns",
	}

	return &agentSimulationJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *agentSimulationJSONClient) CreateSimulationRun(ctx context.Context, in *CreateSimulationRunRequest) (*CreateSimulationRunResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentSimulation")
	ctx = ctxsetters.WithMethodName(ctx, "CreateSimulationRun")
	caller := c.callCreateSimulationRun
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateSimulationRunRequest) (*CreateSimulationRunResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateSimulationRunRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateSimulationRunRequest) when calling interceptor")
					}
					return c.callCreateSimulationRun(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateSimulationRunResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateSimulationRunResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentSimulationJSONClient) callCreateSimulationRun(ctx context.Context, in *CreateSimulationRunRequest) (*CreateSimulationRunResponse, error) {
	out := new(CreateSimulationRunResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentSimulationJSONClient) GetSimulationRun(ctx context.Context, in *GetSimulationRunRequest) (*GetSimulationRunResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentSimulation")
	ctx = ctxsetters.WithMethodName(ctx, "GetSimulationRun")
	caller := c.callGetSimulationRun
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetSimulationRunRequest) (*GetSimulationRunResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSimulationRunRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSimulationRunRequest) when calling interceptor")
					}
					return c.callGetSimulationRun(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSimulationRunResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSimulationRunResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentSimulationJSONClient) callGetSimulationRun(ctx context.Context, in *GetSimulationRunRequest) (*GetSimulationRunResponse, error) {
	out := new(GetSimulationRunResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *agentSimulationJSONClient) ListSimulationRuns(ctx context.Context, in *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentSimulation")
	ctx = ctxsetters.WithMethodName(ctx, "ListSimulationRuns")
	caller := c.callListSimulationRuns
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListSimulationRunsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListSimulationRunsRequest) when calling interceptor")
					}
					return c.callListSimulationRuns(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListSimulationRunsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListSimulationRunsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *agentSimulationJSONClient) callListSimulationRuns(ctx context.Context, in *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error) {
	out := new(ListSimulationRunsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==============================
// AgentSimulation Server Handler
// ==============================

type agentSimulationServer struct {
	AgentSimulation
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewAgentSimulationServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewAgentSimulationServer(svc AgentSimulation, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &agentSimulationServer{
		AgentSimulation:  svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *agentSimulationServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *agentSimulationServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// AgentSimulationPathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const AgentSimulationPathPrefix = "/twirp/livekit.AgentSimulation/"

func (s *agentSimulationServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "AgentSimulation")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "livekit.AgentSimulation" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "CreateSimulationRun":
		s.serveCreateSimulationRun(ctx, resp, req)
		return
	case "GetSimulationRun":
		s.serveGetSimulationRun(ctx, resp, req)
		return
	case "ListSimulationRuns":
		s.serveListSimulationRuns(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *agentSimulationServer) serveCreateSimulationRun(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreateSimulationRunJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreateSimulationRunProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *agentSimulationServer) serveCreateSimulationRunJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateSimulationRun")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreateSimulationRunRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AgentSimulation.CreateSimulationRun
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateSimulationRunRequest) (*CreateSimulationRunResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateSimulationRunRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateSimulationRunRequest) when calling interceptor")
					}
					return s.AgentSimulation.CreateSimulationRun(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateSimulationRunResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateSimulationRunResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreateSimulationRunResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateSimulationRunResponse and nil error while calling CreateSimulationRun. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentSimulationServer) serveCreateSimulationRunProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateSimulationRun")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreateSimulationRunRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AgentSimulation.CreateSimulationRun
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateSimulationRunRequest) (*CreateSimulationRunResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateSimulationRunRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateSimulationRunRequest) when calling interceptor")
					}
					return s.AgentSimulation.CreateSimulationRun(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateSimulationRunResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateSimulationRunResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreateSimulationRunResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateSimulationRunResponse and nil error while calling CreateSimulationRun. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentSimulationServer) serveGetSimulationRun(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetSimulationRunJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetSimulationRunProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *agentSimulationServer) serveGetSimulationRunJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetSimulationRun")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetSimulationRunRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AgentSimulation.GetSimulationRun
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetSimulationRunRequest) (*GetSimulationRunResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSimulationRunRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSimulationRunRequest) when calling interceptor")
					}
					return s.AgentSimulation.GetSimulationRun(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSimulationRunResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSimulationRunResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetSimulationRunResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetSimulationRunResponse and nil error while calling GetSimulationRun. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentSimulationServer) serveGetSimulationRunProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetSimulationRun")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetSimulationRunRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AgentSimulation.GetSimulationRun
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetSimulationRunRequest) (*GetSimulationRunResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSimulationRunRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSimulationRunRequest) when calling interceptor")
					}
					return s.AgentSimulation.GetSimulationRun(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSimulationRunResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSimulationRunResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetSimulationRunResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetSimulationRunResponse and nil error while calling GetSimulationRun. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentSimulationServer) serveListSimulationRuns(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListSimulationRunsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListSimulationRunsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *agentSimulationServer) serveListSimulationRunsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListSimulationRuns")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListSimulationRunsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AgentSimulation.ListSimulationRuns
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListSimulationRunsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListSimulationRunsRequest) when calling interceptor")
					}
					return s.AgentSimulation.ListSimulationRuns(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListSimulationRunsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListSimulationRunsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListSimulationRunsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListSimulationRunsResponse and nil error while calling ListSimulationRuns. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentSimulationServer) serveListSimulationRunsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListSimulationRuns")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListSimulationRunsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AgentSimulation.ListSimulationRuns
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListSimulationRunsRequest) (*ListSimulationRunsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListSimulationRunsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListSimulationRunsRequest) when calling interceptor")
					}
					return s.AgentSimulation.ListSimulationRuns(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListSimulationRunsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListSimulationRunsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListSimulationRunsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListSimulationRunsResponse and nil error while calling ListSimulationRuns. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *agentSimulationServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor8, 0
}

func (s *agentSimulationServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *agentSimulationServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "livekit", "AgentSimulation")
}

var twirpFileDescriptor8 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x51, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x76, 0x9a, 0x2a, 0x53, 0x9a, 0x3a, 0x4b, 0x01, 0x63, 0x54, 0x94, 0xba, 0x48, 0x44,
	0x20, 0xb9, 0x52, 0x10, 0x1f, 0xf4, 0x2f, 0x34, 0x6e, 0x49, 0x09, 0xa6, 0x72, 0x52, 0x21, 0x10,
	0xc8, 0x38, 0xf6, 0xaa, 0x6c, 0xa9, 0xed, 0xe0, 0x5d, 0xf7, 0x1e, 0x5c, 0x03, 0xce, 0xc2, 0x31,
	0xf8, 0xe1, 0x14, 0xc8, 0xeb, 0xc5, 0x49, 0x1a, 0x3b, 0xe2, 0x83, 0x4f, 0xbf, 0x79, 0xf3, 0x66,
	0xe6, 0xcd, 0xac, 0xe1, 0xc1, 0x25, 0xb9, 0xc2, 0x5f, 0x08, 0x73, 0xbd, 0x73, 0x1c, 0x31, 0x97,
	0x92, 0x30, 0xbd, 0xf4, 0x18, 0x89, 0x23, 0x73, 0x9a, 0xc4, 0x2c, 0x46, 0xeb, 0x22, 0x6e, 0xfc,
	0xac, 0xc1, 0xe6, 0xa8, 0x88, 0x3a, 0x69, 0x84, 0x9a, 0x20, 0x93, 0x40, 0x93, 0xda, 0x52, 0xa7,
	0xe1, 0xc8, 0x24, 0x40, 0x3b, 0x00, 0xd3, 0x24, 0xbe, 0xc0, 0x3e, 0x73, 0x49, 0xa0, 0xc9, 0x1c,
	0x6f, 0x08, 0x64, 0x10, 0xa0, 0x67, 0x50, 0xa7, 0xcc, 0x63, 0x29, 0xd5, 0x94, 0xb6, 0xd4, 0x69,
	0x76, 0x77, 0x4c, 0x21, 0x6d, 0x2e, 0xc8, 0x9a, 0x23, 0x4e, 0x72, 0x04, 0x19, 0x3d, 0x81, 0x56,
	0xde, 0x5a, 0x80, 0xa9, 0x9f, 0x90, 0x69, 0x46, 0xd3, 0x6a, 0x5c, 0x5c, 0xe5, 0x81, 0xfe, 0x0c,
	0x47, 0xdb, 0xb0, 0x86, 0x93, 0x24, 0x4e, 0xb4, 0x35, 0x4e, 0xc8, 0x3f, 0xb2, 0xc6, 0xfc, 0x04,
	0x7b, 0x0c, 0x07, 0xae, 0xc7, 0xb4, 0x7a, 0x5b, 0xea, 0x28, 0x4e, 0x43, 0x20, 0x3d, 0x86, 0x4c,
	0xa8, 0x5d, 0xc4, 0x13, 0xaa, 0xad, 0xb7, 0x95, 0xce, 0x46, 0x57, 0xaf, 0x68, 0xeb, 0x24, 0x9e,
	0x38, 0x9c, 0xa7, 0xff, 0x92, 0x40, 0x39, 0x89, 0x27, 0x4b, 0xf3, 0x3f, 0x2f, 0x06, 0x94, 0xf9,
	0x80, 0xbb, 0xd5, 0x4a, 0xd7, 0x87, 0x34, 0xe0, 0x26, 0x89, 0x28, 0x4b, 0x52, 0x3f, 0x23, 0xe5,
	0x0e, 0x35, 0x9c, 0x05, 0x6c, 0x36, 0x5b, 0x6d, 0x6e, 0x36, 0xe3, 0x1d, 0xd4, 0x73, 0x2d, 0x84,
	0xa0, 0x39, 0x1a, 0xf7, 0xc6, 0x67, 0x23, 0xf7, 0xd4, 0xb2, 0xfb, 0x03, 0xfb, 0x58, 0xbd, 0x31,
	0x87, 0x39, 0x67, 0xb6, 0x9d, 0x61, 0x12, 0xda, 0x06, 0x55, 0x60, 0x87, 0x6f, 0x5e, 0x9f, 0x0e,
	0xad, 0xb1, 0xd5, 0x57, 0x65, 0xd4, 0x82, 0x4d, 0x81, 0x1e, 0xf5, 0x06, 0x43, 0xab, 0xaf, 0x2a,
	0xc6, 0x87, 0x42, 0xfa, 0x36, 0xb4, 0x44, 0xf0, 0xd8, 0xb2, 0x2d, 0xa7, 0x37, 0xfe, 0x0f, 0xea,
	0xdf, 0x24, 0xd0, 0x0f, 0xf9, 0x0e, 0x16, 0xdc, 0x71, 0xf0, 0xd7, 0x14, 0x53, 0x96, 0xed, 0x2c,
	0x5f, 0x7b, 0xe4, 0x85, 0x58, 0x98, 0xdc, 0xe0, 0x88, 0xed, 0x85, 0xb8, 0xfc, 0x2a, 0xe4, 0x8a,
	0xab, 0x78, 0x04, 0x5b, 0x51, 0x1a, 0xce, 0xdd, 0x76, 0x6e, 0xf0, 0x9a, 0xd3, 0x8c, 0xd2, 0x70,
	0x56, 0x9d, 0x1a, 0x03, 0xb8, 0x5f, 0xda, 0x12, 0x9d, 0xc6, 0x11, 0xc5, 0xe8, 0x31, 0xb4, 0x66,
	0x1a, 0x6e, 0x92, 0x46, 0x6e, 0xb1, 0xff, 0x2d, 0x3a, 0x9f, 0x31, 0x08, 0x8c, 0x00, 0xee, 0x1e,
	0x63, 0x56, 0x35, 0xda, 0xdc, 0x3b, 0x91, 0xae, 0xbf, 0x93, 0xd2, 0x2a, 0x72, 0x79, 0x95, 0x3e,
	0x68, 0xcb, 0x55, 0x44, 0xb7, 0x1d, 0x50, 0x92, 0x34, 0xe2, 0xfa, 0x1b, 0xdd, 0x3b, 0xe5, 0xb7,
	0xe8, 0x64, 0x14, 0xe3, 0x00, 0xee, 0x0d, 0x09, 0x5d, 0x94, 0xa1, 0xff, 0xd6, 0xad, 0xf1, 0x12,
	0xf4, 0xb2, 0xdc, 0xc2, 0xb1, 0x5a, 0x92, 0x46, 0x54, 0x93, 0xf8, 0xd3, 0xaa, 0x6a, 0x82, 0x73,
	0xba, 0x3f, 0x64, 0xd8, 0xea, 0x65, 0xab, 0x9b, 0x05, 0xd1, 0x27, 0xb8, 0x55, 0xb2, 0x10, 0xb4,
	0x57, 0x08, 0x55, 0x5f, 0x90, 0xfe, 0x70, 0x35, 0x49, 0x74, 0xf8, 0x16, 0xd4, 0xeb, 0x0e, 0xa2,
	0x76, 0x91, 0x59, 0xb1, 0x42, 0x7d, 0x77, 0x05, 0x43, 0x08, 0x7f, 0x04, 0xb4, 0x6c, 0x0c, 0x32,
	0x8a, 0xc4, 0x4a, 0xc7, 0xf5, 0xbd, 0x95, 0x9c, 0x5c, 0xfe, 0xc5, 0xd1, 0xfb, 0xbd, 0x73, 0xc2,
	0x3e, 0xa7, 0x13, 0xd3, 0x8f, 0xc3, 0x7d, 0x91, 0xb0, 0xcf, 0xff, 0xd9, 0x7e, 0x7c, 0xf9, 0x17,
	0xf8, 0x2e, 0x6f, 0x0e, 0xc9, 0x15, 0x7e, 0x45, 0x98, 0x79, 0x9a, 0x85, 0x7e, 0xcb, 0x4d, 0xf1,
	0x7d, 0x70, 0xc0, 0x81, 0x49, 0x9d, 0xa7, 0x3c, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x13, 0x6c,
	0x92, 0x7e, 0x08, 0x06, 0x00, 0x00,
}
