// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.23.4
// source: livekit_rtc_v2.proto

package livekit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signalv2WireMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Signalv2WireMessage_Envelope
	//	*Signalv2WireMessage_Fragment
	Message       isSignalv2WireMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signalv2WireMessage) Reset() {
	*x = Signalv2WireMessage{}
	mi := &file_livekit_rtc_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signalv2WireMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signalv2WireMessage) ProtoMessage() {}

func (x *Signalv2WireMessage) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_rtc_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signalv2WireMessage.ProtoReflect.Descriptor instead.
func (*Signalv2WireMessage) Descriptor() ([]byte, []int) {
	return file_livekit_rtc_v2_proto_rawDescGZIP(), []int{0}
}

func (x *Signalv2WireMessage) GetMessage() isSignalv2WireMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Signalv2WireMessage) GetEnvelope() *Envelope {
	if x != nil {
		if x, ok := x.Message.(*Signalv2WireMessage_Envelope); ok {
			return x.Envelope
		}
	}
	return nil
}

func (x *Signalv2WireMessage) GetFragment() *Fragment {
	if x != nil {
		if x, ok := x.Message.(*Signalv2WireMessage_Fragment); ok {
			return x.Fragment
		}
	}
	return nil
}

type isSignalv2WireMessage_Message interface {
	isSignalv2WireMessage_Message()
}

type Signalv2WireMessage_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope,proto3,oneof"`
}

type Signalv2WireMessage_Fragment struct {
	Fragment *Fragment `protobuf:"bytes,2,opt,name=fragment,proto3,oneof"`
}

func (*Signalv2WireMessage_Envelope) isSignalv2WireMessage_Message() {}

func (*Signalv2WireMessage_Fragment) isSignalv2WireMessage_Message() {}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// collection of client -> server messages
	ClientMessages []*Signalv2ClientMessage `protobuf:"bytes,1,rep,name=client_messages,json=clientMessages,proto3" json:"client_messages,omitempty"`
	// collection of server -> client messages
	ServerMessages []*Signalv2ServerMessage `protobuf:"bytes,2,rep,name=server_messages,json=serverMessages,proto3" json:"server_messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_livekit_rtc_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_rtc_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_livekit_rtc_v2_proto_rawDescGZIP(), []int{1}
}

func (x *Envelope) GetClientMessages() []*Signalv2ClientMessage {
	if x != nil {
		return x.ClientMessages
	}
	return nil
}

func (x *Envelope) GetServerMessages() []*Signalv2ServerMessage {
	if x != nil {
		return x.ServerMessages
	}
	return nil
}

type Sequencer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// monotonically increasing number (by 1) starting at some non-zero number (should not rollover)
	MessageId uint32 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// last remote message processed
	LastProcessedRemoteMessageId uint32 `protobuf:"varint,2,opt,name=last_processed_remote_message_id,json=lastProcessedRemoteMessageId,proto3" json:"last_processed_remote_message_id,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Sequencer) Reset() {
	*x = Sequencer{}
	mi := &file_livekit_rtc_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sequencer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sequencer) ProtoMessage() {}

func (x *Sequencer) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_rtc_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sequencer.ProtoReflect.Descriptor instead.
func (*Sequencer) Descriptor() ([]byte, []int) {
	return file_livekit_rtc_v2_proto_rawDescGZIP(), []int{2}
}

func (x *Sequencer) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Sequencer) GetLastProcessedRemoteMessageId() uint32 {
	if x != nil {
		return x.LastProcessedRemoteMessageId
	}
	return 0
}

type Signalv2ClientMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Sequencer *Sequencer             `protobuf:"bytes,1,opt,name=sequencer,proto3" json:"sequencer,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*Signalv2ClientMessage_ConnectRequest
	//	*Signalv2ClientMessage_PublisherSdp
	//	*Signalv2ClientMessage_SubscriberSdp
	Message       isSignalv2ClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signalv2ClientMessage) Reset() {
	*x = Signalv2ClientMessage{}
	mi := &file_livekit_rtc_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signalv2ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signalv2ClientMessage) ProtoMessage() {}

func (x *Signalv2ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_rtc_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signalv2ClientMessage.ProtoReflect.Descriptor instead.
func (*Signalv2ClientMessage) Descriptor() ([]byte, []int) {
	return file_livekit_rtc_v2_proto_rawDescGZIP(), []int{3}
}

func (x *Signalv2ClientMessage) GetSequencer() *Sequencer {
	if x != nil {
		return x.Sequencer
	}
	return nil
}

func (x *Signalv2ClientMessage) GetMessage() isSignalv2ClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Signalv2ClientMessage) GetConnectRequest() *ConnectRequest {
	if x != nil {
		if x, ok := x.Message.(*Signalv2ClientMessage_ConnectRequest); ok {
			return x.ConnectRequest
		}
	}
	return nil
}

func (x *Signalv2ClientMessage) GetPublisherSdp() *SessionDescription {
	if x != nil {
		if x, ok := x.Message.(*Signalv2ClientMessage_PublisherSdp); ok {
			return x.PublisherSdp
		}
	}
	return nil
}

func (x *Signalv2ClientMessage) GetSubscriberSdp() *SessionDescription {
	if x != nil {
		if x, ok := x.Message.(*Signalv2ClientMessage_SubscriberSdp); ok {
			return x.SubscriberSdp
		}
	}
	return nil
}

type isSignalv2ClientMessage_Message interface {
	isSignalv2ClientMessage_Message()
}

type Signalv2ClientMessage_ConnectRequest struct {
	ConnectRequest *ConnectRequest `protobuf:"bytes,2,opt,name=connect_request,json=connectRequest,proto3,oneof"`
}

type Signalv2ClientMessage_PublisherSdp struct {
	PublisherSdp *SessionDescription `protobuf:"bytes,3,opt,name=publisher_sdp,json=publisherSdp,proto3,oneof"` // SDP offer for publisher peer connection
}

type Signalv2ClientMessage_SubscriberSdp struct {
	SubscriberSdp *SessionDescription `protobuf:"bytes,4,opt,name=subscriber_sdp,json=subscriberSdp,proto3,oneof"` // SDP answer for subscriber peer connection
}

func (*Signalv2ClientMessage_ConnectRequest) isSignalv2ClientMessage_Message() {}

func (*Signalv2ClientMessage_PublisherSdp) isSignalv2ClientMessage_Message() {}

func (*Signalv2ClientMessage_SubscriberSdp) isSignalv2ClientMessage_Message() {}

type Signalv2ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Sequencer *Sequencer             `protobuf:"bytes,1,opt,name=sequencer,proto3" json:"sequencer,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*Signalv2ServerMessage_ConnectResponse
	//	*Signalv2ServerMessage_PublisherSdp
	//	*Signalv2ServerMessage_SubscriberSdp
	//	*Signalv2ServerMessage_RoomUpdate
	//	*Signalv2ServerMessage_ParticipantUpdate
	Message       isSignalv2ServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signalv2ServerMessage) Reset() {
	*x = Signalv2ServerMessage{}
	mi := &file_livekit_rtc_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signalv2ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signalv2ServerMessage) ProtoMessage() {}

func (x *Signalv2ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_rtc_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signalv2ServerMessage.ProtoReflect.Descriptor instead.
func (*Signalv2ServerMessage) Descriptor() ([]byte, []int) {
	return file_livekit_rtc_v2_proto_rawDescGZIP(), []int{4}
}

func (x *Signalv2ServerMessage) GetSequencer() *Sequencer {
	if x != nil {
		return x.Sequencer
	}
	return nil
}

func (x *Signalv2ServerMessage) GetMessage() isSignalv2ServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Signalv2ServerMessage) GetConnectResponse() *ConnectResponse {
	if x != nil {
		if x, ok := x.Message.(*Signalv2ServerMessage_ConnectResponse); ok {
			return x.ConnectResponse
		}
	}
	return nil
}

func (x *Signalv2ServerMessage) GetPublisherSdp() *SessionDescription {
	if x != nil {
		if x, ok := x.Message.(*Signalv2ServerMessage_PublisherSdp); ok {
			return x.PublisherSdp
		}
	}
	return nil
}

func (x *Signalv2ServerMessage) GetSubscriberSdp() *SessionDescription {
	if x != nil {
		if x, ok := x.Message.(*Signalv2ServerMessage_SubscriberSdp); ok {
			return x.SubscriberSdp
		}
	}
	return nil
}

func (x *Signalv2ServerMessage) GetRoomUpdate() *RoomUpdate {
	if x != nil {
		if x, ok := x.Message.(*Signalv2ServerMessage_RoomUpdate); ok {
			return x.RoomUpdate
		}
	}
	return nil
}

func (x *Signalv2ServerMessage) GetParticipantUpdate() *ParticipantUpdate {
	if x != nil {
		if x, ok := x.Message.(*Signalv2ServerMessage_ParticipantUpdate); ok {
			return x.ParticipantUpdate
		}
	}
	return nil
}

type isSignalv2ServerMessage_Message interface {
	isSignalv2ServerMessage_Message()
}

type Signalv2ServerMessage_ConnectResponse struct {
	ConnectResponse *ConnectResponse `protobuf:"bytes,2,opt,name=connect_response,json=connectResponse,proto3,oneof"`
}

type Signalv2ServerMessage_PublisherSdp struct {
	PublisherSdp *SessionDescription `protobuf:"bytes,3,opt,name=publisher_sdp,json=publisherSdp,proto3,oneof"` // SDP answer for publisher peer connection
}

type Signalv2ServerMessage_SubscriberSdp struct {
	SubscriberSdp *SessionDescription `protobuf:"bytes,4,opt,name=subscriber_sdp,json=subscriberSdp,proto3,oneof"` // SDP offer for subscriber peer connection
}

type Signalv2ServerMessage_RoomUpdate struct {
	RoomUpdate *RoomUpdate `protobuf:"bytes,5,opt,name=room_update,json=roomUpdate,proto3,oneof"`
}

type Signalv2ServerMessage_ParticipantUpdate struct {
	ParticipantUpdate *ParticipantUpdate `protobuf:"bytes,6,opt,name=participant_update,json=participantUpdate,proto3,oneof"`
}

func (*Signalv2ServerMessage_ConnectResponse) isSignalv2ServerMessage_Message() {}

func (*Signalv2ServerMessage_PublisherSdp) isSignalv2ServerMessage_Message() {}

func (*Signalv2ServerMessage_SubscriberSdp) isSignalv2ServerMessage_Message() {}

func (*Signalv2ServerMessage_RoomUpdate) isSignalv2ServerMessage_Message() {}

func (*Signalv2ServerMessage_ParticipantUpdate) isSignalv2ServerMessage_Message() {}

type ConnectionSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AutoSubscribe        bool                   `protobuf:"varint,1,opt,name=auto_subscribe,json=autoSubscribe,proto3" json:"auto_subscribe,omitempty"`
	AdaptiveStream       bool                   `protobuf:"varint,2,opt,name=adaptive_stream,json=adaptiveStream,proto3" json:"adaptive_stream,omitempty"`
	SubscriberAllowPause *bool                  `protobuf:"varint,3,opt,name=subscriber_allow_pause,json=subscriberAllowPause,proto3,oneof" json:"subscriber_allow_pause,omitempty"`
	DisableIceLite       bool                   `protobuf:"varint,4,opt,name=disable_ice_lite,json=disableIceLite,proto3" json:"disable_ice_lite,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConnectionSettings) Reset() {
	*x = ConnectionSettings{}
	mi := &file_livekit_rtc_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSettings) ProtoMessage() {}

func (x *ConnectionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_rtc_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionSettings.ProtoReflect.Descriptor instead.
func (*ConnectionSettings) Descriptor() ([]byte, []int) {
	return file_livekit_rtc_v2_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectionSettings) GetAutoSubscribe() bool {
	if x != nil {
		return x.AutoSubscribe
	}
	return false
}

func (x *ConnectionSettings) GetAdaptiveStream() bool {
	if x != nil {
		return x.AdaptiveStream
	}
	return false
}

func (x *ConnectionSettings) GetSubscriberAllowPause() bool {
	if x != nil && x.SubscriberAllowPause != nil {
		return *x.SubscriberAllowPause
	}
	return false
}

func (x *ConnectionSettings) GetDisableIceLite() bool {
	if x != nil {
		return x.DisableIceLite
	}
	return false
}

type ConnectRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientInfo         *ClientInfo            `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	ConnectionSettings *ConnectionSettings    `protobuf:"bytes,2,opt,name=connection_settings,json=connectionSettings,proto3" json:"connection_settings,omitempty"`
	Metadata           string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // if not empty, will overwrite `metadata` in token
	// will set keys provided via this
	// will overwrite if the same key is in the token
	// will not delete keys from token if there is a key collision and this sets that key to empty value
	ParticipantAttributes map[string]string `protobuf:"bytes,4,rep,name=participant_attributes,json=participantAttributes,proto3" json:"participant_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_livekit_rtc_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_rtc_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_livekit_rtc_v2_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectRequest) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

func (x *ConnectRequest) GetConnectionSettings() *ConnectionSettings {
	if x != nil {
		return x.ConnectionSettings
	}
	return nil
}

func (x *ConnectRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *ConnectRequest) GetParticipantAttributes() map[string]string {
	if x != nil {
		return x.ParticipantAttributes
	}
	return nil
}

type ConnectResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Room                *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Participant         *ParticipantInfo       `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"`
	OtherParticipants   []*ParticipantInfo     `protobuf:"bytes,3,rep,name=other_participants,json=otherParticipants,proto3" json:"other_participants,omitempty"`
	IceServers          []*ICEServer           `protobuf:"bytes,4,rep,name=ice_servers,json=iceServers,proto3" json:"ice_servers,omitempty"`
	ClientConfiguration *ClientConfiguration   `protobuf:"bytes,5,opt,name=client_configuration,json=clientConfiguration,proto3" json:"client_configuration,omitempty"`
	ServerInfo          *ServerInfo            `protobuf:"bytes,6,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	// Server-Injected-Frame byte trailer, used to identify unencrypted frames when e2ee is enabled
	SifTrailer           []byte              `protobuf:"bytes,7,opt,name=sif_trailer,json=sifTrailer,proto3" json:"sif_trailer,omitempty"`
	EnabledPublishCodecs []*Codec            `protobuf:"bytes,8,rep,name=enabled_publish_codecs,json=enabledPublishCodecs,proto3" json:"enabled_publish_codecs,omitempty"`
	FastPublish          bool                `protobuf:"varint,9,opt,name=fast_publish,json=fastPublish,proto3" json:"fast_publish,omitempty"`
	SubscriberSdp        *SessionDescription `protobuf:"bytes,10,opt,name=subscriber_sdp,json=subscriberSdp,proto3" json:"subscriber_sdp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_livekit_rtc_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_rtc_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_livekit_rtc_v2_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *ConnectResponse) GetParticipant() *ParticipantInfo {
	if x != nil {
		return x.Participant
	}
	return nil
}

func (x *ConnectResponse) GetOtherParticipants() []*ParticipantInfo {
	if x != nil {
		return x.OtherParticipants
	}
	return nil
}

func (x *ConnectResponse) GetIceServers() []*ICEServer {
	if x != nil {
		return x.IceServers
	}
	return nil
}

func (x *ConnectResponse) GetClientConfiguration() *ClientConfiguration {
	if x != nil {
		return x.ClientConfiguration
	}
	return nil
}

func (x *ConnectResponse) GetServerInfo() *ServerInfo {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

func (x *ConnectResponse) GetSifTrailer() []byte {
	if x != nil {
		return x.SifTrailer
	}
	return nil
}

func (x *ConnectResponse) GetEnabledPublishCodecs() []*Codec {
	if x != nil {
		return x.EnabledPublishCodecs
	}
	return nil
}

func (x *ConnectResponse) GetFastPublish() bool {
	if x != nil {
		return x.FastPublish
	}
	return false
}

func (x *ConnectResponse) GetSubscriberSdp() *SessionDescription {
	if x != nil {
		return x.SubscriberSdp
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint32                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_livekit_rtc_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_rtc_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_livekit_rtc_v2_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResponse) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_livekit_rtc_v2_proto protoreflect.FileDescriptor

const file_livekit_rtc_v2_proto_rawDesc = "" +
	"\n" +
	"\x14livekit_rtc_v2.proto\x12\alivekit\x1a\x11livekit_rtc.proto\x1a\x14livekit_models.proto\"\x82\x01\n" +
	"\x13Signalv2WireMessage\x12/\n" +
	"\benvelope\x18\x01 \x01(\v2\x11.livekit.EnvelopeH\x00R\benvelope\x12/\n" +
	"\bfragment\x18\x02 \x01(\v2\x11.livekit.FragmentH\x00R\bfragmentB\t\n" +
	"\amessage\"\x9c\x01\n" +
	"\bEnvelope\x12G\n" +
	"\x0fclient_messages\x18\x01 \x03(\v2\x1e.livekit.Signalv2ClientMessageR\x0eclientMessages\x12G\n" +
	"\x0fserver_messages\x18\x02 \x03(\v2\x1e.livekit.Signalv2ServerMessageR\x0eserverMessages\"r\n" +
	"\tSequencer\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\rR\tmessageId\x12F\n" +
	" last_processed_remote_message_id\x18\x02 \x01(\rR\x1clastProcessedRemoteMessageId\"\xa2\x02\n" +
	"\x15Signalv2ClientMessage\x120\n" +
	"\tsequencer\x18\x01 \x01(\v2\x12.livekit.SequencerR\tsequencer\x12B\n" +
	"\x0fconnect_request\x18\x02 \x01(\v2\x17.livekit.ConnectRequestH\x00R\x0econnectRequest\x12B\n" +
	"\rpublisher_sdp\x18\x03 \x01(\v2\x1b.livekit.SessionDescriptionH\x00R\fpublisherSdp\x12D\n" +
	"\x0esubscriber_sdp\x18\x04 \x01(\v2\x1b.livekit.SessionDescriptionH\x00R\rsubscriberSdpB\t\n" +
	"\amessage\"\xaa\x03\n" +
	"\x15Signalv2ServerMessage\x120\n" +
	"\tsequencer\x18\x01 \x01(\v2\x12.livekit.SequencerR\tsequencer\x12E\n" +
	"\x10connect_response\x18\x02 \x01(\v2\x18.livekit.ConnectResponseH\x00R\x0fconnectResponse\x12B\n" +
	"\rpublisher_sdp\x18\x03 \x01(\v2\x1b.livekit.SessionDescriptionH\x00R\fpublisherSdp\x12D\n" +
	"\x0esubscriber_sdp\x18\x04 \x01(\v2\x1b.livekit.SessionDescriptionH\x00R\rsubscriberSdp\x126\n" +
	"\vroom_update\x18\x05 \x01(\v2\x13.livekit.RoomUpdateH\x00R\n" +
	"roomUpdate\x12K\n" +
	"\x12participant_update\x18\x06 \x01(\v2\x1a.livekit.ParticipantUpdateH\x00R\x11participantUpdateB\t\n" +
	"\amessage\"\xe4\x01\n" +
	"\x12ConnectionSettings\x12%\n" +
	"\x0eauto_subscribe\x18\x01 \x01(\bR\rautoSubscribe\x12'\n" +
	"\x0fadaptive_stream\x18\x02 \x01(\bR\x0eadaptiveStream\x129\n" +
	"\x16subscriber_allow_pause\x18\x03 \x01(\bH\x00R\x14subscriberAllowPause\x88\x01\x01\x12(\n" +
	"\x10disable_ice_lite\x18\x04 \x01(\bR\x0edisableIceLiteB\x19\n" +
	"\x17_subscriber_allow_pause\"\xe5\x02\n" +
	"\x0eConnectRequest\x124\n" +
	"\vclient_info\x18\x01 \x01(\v2\x13.livekit.ClientInfoR\n" +
	"clientInfo\x12L\n" +
	"\x13connection_settings\x18\x02 \x01(\v2\x1b.livekit.ConnectionSettingsR\x12connectionSettings\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12i\n" +
	"\x16participant_attributes\x18\x04 \x03(\v22.livekit.ConnectRequest.ParticipantAttributesEntryR\x15participantAttributes\x1aH\n" +
	"\x1aParticipantAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x04\n" +
	"\x0fConnectResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.livekit.RoomR\x04room\x12:\n" +
	"\vparticipant\x18\x02 \x01(\v2\x18.livekit.ParticipantInfoR\vparticipant\x12G\n" +
	"\x12other_participants\x18\x03 \x03(\v2\x18.livekit.ParticipantInfoR\x11otherParticipants\x123\n" +
	"\vice_servers\x18\x04 \x03(\v2\x12.livekit.ICEServerR\n" +
	"iceServers\x12O\n" +
	"\x14client_configuration\x18\x05 \x01(\v2\x1c.livekit.ClientConfigurationR\x13clientConfiguration\x124\n" +
	"\vserver_info\x18\x06 \x01(\v2\x13.livekit.ServerInfoR\n" +
	"serverInfo\x12\x1f\n" +
	"\vsif_trailer\x18\a \x01(\fR\n" +
	"sifTrailer\x12D\n" +
	"\x16enabled_publish_codecs\x18\b \x03(\v2\x0e.livekit.CodecR\x14enabledPublishCodecs\x12!\n" +
	"\ffast_publish\x18\t \x01(\bR\vfastPublish\x12B\n" +
	"\x0esubscriber_sdp\x18\n" +
	" \x01(\v2\x1b.livekit.SessionDescriptionR\rsubscriberSdp\"D\n" +
	"\rErrorResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\rR\tmessageId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorBFZ#github.com/livekit/protocol/livekit\xaa\x02\rLiveKit.Proto\xea\x02\x0eLiveKit::Protob\x06proto3"

var (
	file_livekit_rtc_v2_proto_rawDescOnce sync.Once
	file_livekit_rtc_v2_proto_rawDescData []byte
)

func file_livekit_rtc_v2_proto_rawDescGZIP() []byte {
	file_livekit_rtc_v2_proto_rawDescOnce.Do(func() {
		file_livekit_rtc_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livekit_rtc_v2_proto_rawDesc), len(file_livekit_rtc_v2_proto_rawDesc)))
	})
	return file_livekit_rtc_v2_proto_rawDescData
}

var file_livekit_rtc_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_livekit_rtc_v2_proto_goTypes = []any{
	(*Signalv2WireMessage)(nil),   // 0: livekit.Signalv2WireMessage
	(*Envelope)(nil),              // 1: livekit.Envelope
	(*Sequencer)(nil),             // 2: livekit.Sequencer
	(*Signalv2ClientMessage)(nil), // 3: livekit.Signalv2ClientMessage
	(*Signalv2ServerMessage)(nil), // 4: livekit.Signalv2ServerMessage
	(*ConnectionSettings)(nil),    // 5: livekit.ConnectionSettings
	(*ConnectRequest)(nil),        // 6: livekit.ConnectRequest
	(*ConnectResponse)(nil),       // 7: livekit.ConnectResponse
	(*ErrorResponse)(nil),         // 8: livekit.ErrorResponse
	nil,                           // 9: livekit.ConnectRequest.ParticipantAttributesEntry
	(*Fragment)(nil),              // 10: livekit.Fragment
	(*SessionDescription)(nil),    // 11: livekit.SessionDescription
	(*RoomUpdate)(nil),            // 12: livekit.RoomUpdate
	(*ParticipantUpdate)(nil),     // 13: livekit.ParticipantUpdate
	(*ClientInfo)(nil),            // 14: livekit.ClientInfo
	(*Room)(nil),                  // 15: livekit.Room
	(*ParticipantInfo)(nil),       // 16: livekit.ParticipantInfo
	(*ICEServer)(nil),             // 17: livekit.ICEServer
	(*ClientConfiguration)(nil),   // 18: livekit.ClientConfiguration
	(*ServerInfo)(nil),            // 19: livekit.ServerInfo
	(*Codec)(nil),                 // 20: livekit.Codec
}
var file_livekit_rtc_v2_proto_depIdxs = []int32{
	1,  // 0: livekit.Signalv2WireMessage.envelope:type_name -> livekit.Envelope
	10, // 1: livekit.Signalv2WireMessage.fragment:type_name -> livekit.Fragment
	3,  // 2: livekit.Envelope.client_messages:type_name -> livekit.Signalv2ClientMessage
	4,  // 3: livekit.Envelope.server_messages:type_name -> livekit.Signalv2ServerMessage
	2,  // 4: livekit.Signalv2ClientMessage.sequencer:type_name -> livekit.Sequencer
	6,  // 5: livekit.Signalv2ClientMessage.connect_request:type_name -> livekit.ConnectRequest
	11, // 6: livekit.Signalv2ClientMessage.publisher_sdp:type_name -> livekit.SessionDescription
	11, // 7: livekit.Signalv2ClientMessage.subscriber_sdp:type_name -> livekit.SessionDescription
	2,  // 8: livekit.Signalv2ServerMessage.sequencer:type_name -> livekit.Sequencer
	7,  // 9: livekit.Signalv2ServerMessage.connect_response:type_name -> livekit.ConnectResponse
	11, // 10: livekit.Signalv2ServerMessage.publisher_sdp:type_name -> livekit.SessionDescription
	11, // 11: livekit.Signalv2ServerMessage.subscriber_sdp:type_name -> livekit.SessionDescription
	12, // 12: livekit.Signalv2ServerMessage.room_update:type_name -> livekit.RoomUpdate
	13, // 13: livekit.Signalv2ServerMessage.participant_update:type_name -> livekit.ParticipantUpdate
	14, // 14: livekit.ConnectRequest.client_info:type_name -> livekit.ClientInfo
	5,  // 15: livekit.ConnectRequest.connection_settings:type_name -> livekit.ConnectionSettings
	9,  // 16: livekit.ConnectRequest.participant_attributes:type_name -> livekit.ConnectRequest.ParticipantAttributesEntry
	15, // 17: livekit.ConnectResponse.room:type_name -> livekit.Room
	16, // 18: livekit.ConnectResponse.participant:type_name -> livekit.ParticipantInfo
	16, // 19: livekit.ConnectResponse.other_participants:type_name -> livekit.ParticipantInfo
	17, // 20: livekit.ConnectResponse.ice_servers:type_name -> livekit.ICEServer
	18, // 21: livekit.ConnectResponse.client_configuration:type_name -> livekit.ClientConfiguration
	19, // 22: livekit.ConnectResponse.server_info:type_name -> livekit.ServerInfo
	20, // 23: livekit.ConnectResponse.enabled_publish_codecs:type_name -> livekit.Codec
	11, // 24: livekit.ConnectResponse.subscriber_sdp:type_name -> livekit.SessionDescription
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_livekit_rtc_v2_proto_init() }
func file_livekit_rtc_v2_proto_init() {
	if File_livekit_rtc_v2_proto != nil {
		return
	}
	file_livekit_rtc_proto_init()
	file_livekit_models_proto_init()
	file_livekit_rtc_v2_proto_msgTypes[0].OneofWrappers = []any{
		(*Signalv2WireMessage_Envelope)(nil),
		(*Signalv2WireMessage_Fragment)(nil),
	}
	file_livekit_rtc_v2_proto_msgTypes[3].OneofWrappers = []any{
		(*Signalv2ClientMessage_ConnectRequest)(nil),
		(*Signalv2ClientMessage_PublisherSdp)(nil),
		(*Signalv2ClientMessage_SubscriberSdp)(nil),
	}
	file_livekit_rtc_v2_proto_msgTypes[4].OneofWrappers = []any{
		(*Signalv2ServerMessage_ConnectResponse)(nil),
		(*Signalv2ServerMessage_PublisherSdp)(nil),
		(*Signalv2ServerMessage_SubscriberSdp)(nil),
		(*Signalv2ServerMessage_RoomUpdate)(nil),
		(*Signalv2ServerMessage_ParticipantUpdate)(nil),
	}
	file_livekit_rtc_v2_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livekit_rtc_v2_proto_rawDesc), len(file_livekit_rtc_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_livekit_rtc_v2_proto_goTypes,
		DependencyIndexes: file_livekit_rtc_v2_proto_depIdxs,
		MessageInfos:      file_livekit_rtc_v2_proto_msgTypes,
	}.Build()
	File_livekit_rtc_v2_proto = out.File
	file_livekit_rtc_v2_proto_goTypes = nil
	file_livekit_rtc_v2_proto_depIdxs = nil
}
