// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: livekit_agent_worker.proto

package livekit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerType      string                 `protobuf:"bytes,1,opt,name=worker_type,json=workerType,proto3" json:"worker_type,omitempty"`
	AgentName       string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	ActiveJobs      float32                `protobuf:"fixed32,3,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	SdkVersion      string                 `protobuf:"bytes,4,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	WorkerLoad      float32                `protobuf:"fixed32,5,opt,name=worker_load,json=workerLoad,proto3" json:"worker_load,omitempty"`
	ProtocolVersion int32                  `protobuf:"varint,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_livekit_agent_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_livekit_agent_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerInfo) GetWorkerType() string {
	if x != nil {
		return x.WorkerType
	}
	return ""
}

func (x *WorkerInfo) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *WorkerInfo) GetActiveJobs() float32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *WorkerInfo) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *WorkerInfo) GetWorkerLoad() float32 {
	if x != nil {
		return x.WorkerLoad
	}
	return 0
}

func (x *WorkerInfo) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

var File_livekit_agent_worker_proto protoreflect.FileDescriptor

const file_livekit_agent_worker_proto_rawDesc = "" +
	"\n" +
	"\x1alivekit_agent_worker.proto\x12\alivekit\"\xda\x01\n" +
	"\n" +
	"WorkerInfo\x12\x1f\n" +
	"\vworker_type\x18\x01 \x01(\tR\n" +
	"workerType\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x1f\n" +
	"\vactive_jobs\x18\x03 \x01(\x02R\n" +
	"activeJobs\x12\x1f\n" +
	"\vsdk_version\x18\x04 \x01(\tR\n" +
	"sdkVersion\x12\x1f\n" +
	"\vworker_load\x18\x05 \x01(\x02R\n" +
	"workerLoad\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\x05R\x0fprotocolVersionBFZ#github.com/livekit/protocol/livekit\xaa\x02\rLiveKit.Proto\xea\x02\x0eLiveKit::Protob\x06proto3"

var (
	file_livekit_agent_worker_proto_rawDescOnce sync.Once
	file_livekit_agent_worker_proto_rawDescData []byte
)

func file_livekit_agent_worker_proto_rawDescGZIP() []byte {
	file_livekit_agent_worker_proto_rawDescOnce.Do(func() {
		file_livekit_agent_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livekit_agent_worker_proto_rawDesc), len(file_livekit_agent_worker_proto_rawDesc)))
	})
	return file_livekit_agent_worker_proto_rawDescData
}

var file_livekit_agent_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_livekit_agent_worker_proto_goTypes = []any{
	(*WorkerInfo)(nil), // 0: livekit.WorkerInfo
}
var file_livekit_agent_worker_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_livekit_agent_worker_proto_init() }
func file_livekit_agent_worker_proto_init() {
	if File_livekit_agent_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livekit_agent_worker_proto_rawDesc), len(file_livekit_agent_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_livekit_agent_worker_proto_goTypes,
		DependencyIndexes: file_livekit_agent_worker_proto_depIdxs,
		MessageInfos:      file_livekit_agent_worker_proto_msgTypes,
	}.Build()
	File_livekit_agent_worker_proto = out.File
	file_livekit_agent_worker_proto_goTypes = nil
	file_livekit_agent_worker_proto_depIdxs = nil
}
