// Copyright 2024 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: livekit_agent_simulation.proto

package livekit

import (
	agent "github.com/livekit/protocol/livekit/agent"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How the simulated user interacts with the agent under test.
type SimulationMode int32

const (
	SimulationMode_SIMULATION_MODE_UNSPECIFIED SimulationMode = 0
	// The simulator chats over text streams (no audio).
	SimulationMode_SIMULATION_MODE_TEXT SimulationMode = 1
	// The simulator publishes/subscribes audio in the room.
	SimulationMode_SIMULATION_MODE_AUDIO SimulationMode = 2
)

// Enum value maps for SimulationMode.
var (
	SimulationMode_name = map[int32]string{
		0: "SIMULATION_MODE_UNSPECIFIED",
		1: "SIMULATION_MODE_TEXT",
		2: "SIMULATION_MODE_AUDIO",
	}
	SimulationMode_value = map[string]int32{
		"SIMULATION_MODE_UNSPECIFIED": 0,
		"SIMULATION_MODE_TEXT":        1,
		"SIMULATION_MODE_AUDIO":       2,
	}
)

func (x SimulationMode) Enum() *SimulationMode {
	p := new(SimulationMode)
	*p = x
	return p
}

func (x SimulationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_livekit_agent_simulation_proto_enumTypes[0].Descriptor()
}

func (SimulationMode) Type() protoreflect.EnumType {
	return &file_livekit_agent_simulation_proto_enumTypes[0]
}

func (x SimulationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulationMode.Descriptor instead.
func (SimulationMode) EnumDescriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{0}
}

type SimulationRun_Status int32

const (
	SimulationRun_STATUS_PENDING_UPLOAD SimulationRun_Status = 0
	SimulationRun_STATUS_GENERATING     SimulationRun_Status = 1
	SimulationRun_STATUS_RUNNING        SimulationRun_Status = 2
	SimulationRun_STATUS_SUMMARIZING    SimulationRun_Status = 3
	SimulationRun_STATUS_COMPLETED      SimulationRun_Status = 4
	SimulationRun_STATUS_FAILED         SimulationRun_Status = 5
	SimulationRun_STATUS_CANCELLED      SimulationRun_Status = 6
)

// Enum value maps for SimulationRun_Status.
var (
	SimulationRun_Status_name = map[int32]string{
		0: "STATUS_PENDING_UPLOAD",
		1: "STATUS_GENERATING",
		2: "STATUS_RUNNING",
		3: "STATUS_SUMMARIZING",
		4: "STATUS_COMPLETED",
		5: "STATUS_FAILED",
		6: "STATUS_CANCELLED",
	}
	SimulationRun_Status_value = map[string]int32{
		"STATUS_PENDING_UPLOAD": 0,
		"STATUS_GENERATING":     1,
		"STATUS_RUNNING":        2,
		"STATUS_SUMMARIZING":    3,
		"STATUS_COMPLETED":      4,
		"STATUS_FAILED":         5,
		"STATUS_CANCELLED":      6,
	}
)

func (x SimulationRun_Status) Enum() *SimulationRun_Status {
	p := new(SimulationRun_Status)
	*p = x
	return p
}

func (x SimulationRun_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulationRun_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_livekit_agent_simulation_proto_enumTypes[1].Descriptor()
}

func (SimulationRun_Status) Type() protoreflect.EnumType {
	return &file_livekit_agent_simulation_proto_enumTypes[1]
}

func (x SimulationRun_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulationRun_Status.Descriptor instead.
func (SimulationRun_Status) EnumDescriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 0}
}

type SimulationRun_Job_Status int32

const (
	SimulationRun_Job_STATUS_PENDING   SimulationRun_Job_Status = 0
	SimulationRun_Job_STATUS_RUNNING   SimulationRun_Job_Status = 1
	SimulationRun_Job_STATUS_COMPLETED SimulationRun_Job_Status = 2
	SimulationRun_Job_STATUS_FAILED    SimulationRun_Job_Status = 3
	SimulationRun_Job_STATUS_CANCELLED SimulationRun_Job_Status = 4
)

// Enum value maps for SimulationRun_Job_Status.
var (
	SimulationRun_Job_Status_name = map[int32]string{
		0: "STATUS_PENDING",
		1: "STATUS_RUNNING",
		2: "STATUS_COMPLETED",
		3: "STATUS_FAILED",
		4: "STATUS_CANCELLED",
	}
	SimulationRun_Job_Status_value = map[string]int32{
		"STATUS_PENDING":   0,
		"STATUS_RUNNING":   1,
		"STATUS_COMPLETED": 2,
		"STATUS_FAILED":    3,
		"STATUS_CANCELLED": 4,
	}
)

func (x SimulationRun_Job_Status) Enum() *SimulationRun_Job_Status {
	p := new(SimulationRun_Job_Status)
	*p = x
	return p
}

func (x SimulationRun_Job_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulationRun_Job_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_livekit_agent_simulation_proto_enumTypes[2].Descriptor()
}

func (SimulationRun_Job_Status) Type() protoreflect.EnumType {
	return &file_livekit_agent_simulation_proto_enumTypes[2]
}

func (x SimulationRun_Job_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulationRun_Job_Status.Descriptor instead.
func (SimulationRun_Job_Status) EnumDescriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 0, 0}
}

type SimulationRunSummary struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Passed        int32                         `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Failed        int32                         `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	GoingWell     string                        `protobuf:"bytes,3,opt,name=going_well,json=goingWell,proto3" json:"going_well,omitempty"`
	ToImprove     string                        `protobuf:"bytes,4,opt,name=to_improve,json=toImprove,proto3" json:"to_improve,omitempty"`
	Issues        []*SimulationRunSummary_Issue `protobuf:"bytes,5,rep,name=issues,proto3" json:"issues,omitempty"`
	ChatHistory   map[string]*agent.ChatContext `protobuf:"bytes,6,rep,name=chat_history,json=chatHistory,proto3" json:"chat_history,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRunSummary) Reset() {
	*x = SimulationRunSummary{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRunSummary) ProtoMessage() {}

func (x *SimulationRunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRunSummary.ProtoReflect.Descriptor instead.
func (*SimulationRunSummary) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *SimulationRunSummary) GetPassed() int32 {
	if x != nil {
		return x.Passed
	}
	return 0
}

func (x *SimulationRunSummary) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *SimulationRunSummary) GetGoingWell() string {
	if x != nil {
		return x.GoingWell
	}
	return ""
}

func (x *SimulationRunSummary) GetToImprove() string {
	if x != nil {
		return x.ToImprove
	}
	return ""
}

func (x *SimulationRunSummary) GetIssues() []*SimulationRunSummary_Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *SimulationRunSummary) GetChatHistory() map[string]*agent.ChatContext {
	if x != nil {
		return x.ChatHistory
	}
	return nil
}

type SimulationRun struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId        string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status           SimulationRun_Status   `protobuf:"varint,3,opt,name=status,proto3,enum=livekit.SimulationRun_Status" json:"status,omitempty"`
	AgentDescription string                 `protobuf:"bytes,4,opt,name=agent_description,json=agentDescription,proto3" json:"agent_description,omitempty"`
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Jobs             []*SimulationRun_Job   `protobuf:"bytes,7,rep,name=jobs,proto3" json:"jobs,omitempty"`
	AgentName        string                 `protobuf:"bytes,9,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	ScenarioGroup    *ScenarioGroup         `protobuf:"bytes,10,opt,name=scenario_group,json=scenarioGroup,proto3" json:"scenario_group,omitempty"`
	EndedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	JobCount         int32                  `protobuf:"varint,12,opt,name=job_count,json=jobCount,proto3" json:"job_count,omitempty"`
	PassedCount      int32                  `protobuf:"varint,13,opt,name=passed_count,json=passedCount,proto3" json:"passed_count,omitempty"`
	FailedCount      int32                  `protobuf:"varint,14,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	NumSimulations   int32                  `protobuf:"varint,15,opt,name=num_simulations,json=numSimulations,proto3" json:"num_simulations,omitempty"`
	// Aggregate usage across all jobs in this run (sum of Job.usage).
	Usage *SimulationRun_Usage `protobuf:"bytes,16,opt,name=usage,proto3" json:"usage,omitempty"`
	// Maximum simulate jobs running in parallel for this run (0 = server default).
	Concurrency int32 `protobuf:"varint,17,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	// A SimulationRunSummary message, serialized with proto.Marshal and then
	// zstd-compressed: decompress, then proto.Unmarshal into
	// SimulationRunSummary. It stays a plain proto you can decode - it is just
	// compressed by default, so the blob travels storage, PSRPC, and HTTP
	// without re-encoding (a 100-scenario run measured 9.5MB decompressed,
	// ~120KB as this field).
	SummaryZstd   []byte `protobuf:"bytes,18,opt,name=summary_zstd,json=summaryZstd,proto3" json:"summary_zstd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun) Reset() {
	*x = SimulationRun{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun) ProtoMessage() {}

func (x *SimulationRun) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun.ProtoReflect.Descriptor instead.
func (*SimulationRun) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *SimulationRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SimulationRun) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SimulationRun) GetStatus() SimulationRun_Status {
	if x != nil {
		return x.Status
	}
	return SimulationRun_STATUS_PENDING_UPLOAD
}

func (x *SimulationRun) GetAgentDescription() string {
	if x != nil {
		return x.AgentDescription
	}
	return ""
}

func (x *SimulationRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SimulationRun) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SimulationRun) GetJobs() []*SimulationRun_Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *SimulationRun) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *SimulationRun) GetScenarioGroup() *ScenarioGroup {
	if x != nil {
		return x.ScenarioGroup
	}
	return nil
}

func (x *SimulationRun) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *SimulationRun) GetJobCount() int32 {
	if x != nil {
		return x.JobCount
	}
	return 0
}

func (x *SimulationRun) GetPassedCount() int32 {
	if x != nil {
		return x.PassedCount
	}
	return 0
}

func (x *SimulationRun) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *SimulationRun) GetNumSimulations() int32 {
	if x != nil {
		return x.NumSimulations
	}
	return 0
}

func (x *SimulationRun) GetUsage() *SimulationRun_Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *SimulationRun) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *SimulationRun) GetSummaryZstd() []byte {
	if x != nil {
		return x.SummaryZstd
	}
	return nil
}

// A single scenario, mirroring one entry in a scenarios.yaml file. Scenarios
// are no longer stored server-side; the yaml file is the source of truth.
type Scenario struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Label             string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Instructions      string                 `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	AgentExpectations string                 `protobuf:"bytes,3,opt,name=agent_expectations,json=agentExpectations,proto3" json:"agent_expectations,omitempty"`
	// Set as participant attributes on the simulation participant's access token.
	Tags map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Arbitrary JSON-encoded object, surfaced to the agent under test as
	// SimulationContext userdata (e.g. inputs and benchmark target state).
	Userdata      string `protobuf:"bytes,5,opt,name=userdata,proto3" json:"userdata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *Scenario) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Scenario) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *Scenario) GetAgentExpectations() string {
	if x != nil {
		return x.AgentExpectations
	}
	return ""
}

func (x *Scenario) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Scenario) GetUserdata() string {
	if x != nil {
		return x.Userdata
	}
	return ""
}

// A named group of scenarios, mirroring a whole scenarios.yaml file.
type ScenarioGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scenarios     []*Scenario            `protobuf:"bytes,2,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioGroup) Reset() {
	*x = ScenarioGroup{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioGroup) ProtoMessage() {}

func (x *ScenarioGroup) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioGroup.ProtoReflect.Descriptor instead.
func (*ScenarioGroup) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *ScenarioGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScenarioGroup) GetScenarios() []*Scenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

// Carried (protojson-encoded) in the simulation room's metadata so the agent
// under test can read the scenario + run identity synchronously at connect.
type SimulationDispatch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SimulationRunId string                 `protobuf:"bytes,1,opt,name=simulation_run_id,json=simulationRunId,proto3" json:"simulation_run_id,omitempty"`
	JobId           string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Scenario        *Scenario              `protobuf:"bytes,3,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Mode            SimulationMode         `protobuf:"varint,4,opt,name=mode,proto3,enum=livekit.SimulationMode" json:"mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulationDispatch) Reset() {
	*x = SimulationDispatch{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationDispatch) ProtoMessage() {}

func (x *SimulationDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationDispatch.ProtoReflect.Descriptor instead.
func (*SimulationDispatch) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *SimulationDispatch) GetSimulationRunId() string {
	if x != nil {
		return x.SimulationRunId
	}
	return ""
}

func (x *SimulationDispatch) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SimulationDispatch) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

func (x *SimulationDispatch) GetMode() SimulationMode {
	if x != nil {
		return x.Mode
	}
	return SimulationMode_SIMULATION_MODE_UNSPECIFIED
}

type SimulationRunSummary_Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Suggestion    string                 `protobuf:"bytes,2,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRunSummary_Issue) Reset() {
	*x = SimulationRunSummary_Issue{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRunSummary_Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRunSummary_Issue) ProtoMessage() {}

func (x *SimulationRunSummary_Issue) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRunSummary_Issue.ProtoReflect.Descriptor instead.
func (*SimulationRunSummary_Issue) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SimulationRunSummary_Issue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SimulationRunSummary_Issue) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *SimulationRunSummary_Issue) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type SimulationRun_Job struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Id                string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status            SimulationRun_Job_Status `protobuf:"varint,2,opt,name=status,proto3,enum=livekit.SimulationRun_Job_Status" json:"status,omitempty"`
	Instructions      string                   `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	Error             string                   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	AgentExpectations string                   `protobuf:"bytes,5,opt,name=agent_expectations,json=agentExpectations,proto3" json:"agent_expectations,omitempty"`
	Label             string                   `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Tags              []string                 `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	RoomName          string                   `protobuf:"bytes,8,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	StartedAt         *timestamppb.Timestamp   `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt           *timestamppb.Timestamp   `protobuf:"bytes,11,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	RoomId            string                   `protobuf:"bytes,12,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Usage             *SimulationRun_Job_Usage `protobuf:"bytes,13,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SimulationRun_Job) Reset() {
	*x = SimulationRun_Job{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Job) ProtoMessage() {}

func (x *SimulationRun_Job) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Job.ProtoReflect.Descriptor instead.
func (*SimulationRun_Job) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SimulationRun_Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SimulationRun_Job) GetStatus() SimulationRun_Job_Status {
	if x != nil {
		return x.Status
	}
	return SimulationRun_Job_STATUS_PENDING
}

func (x *SimulationRun_Job) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *SimulationRun_Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SimulationRun_Job) GetAgentExpectations() string {
	if x != nil {
		return x.AgentExpectations
	}
	return ""
}

func (x *SimulationRun_Job) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SimulationRun_Job) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SimulationRun_Job) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *SimulationRun_Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SimulationRun_Job) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *SimulationRun_Job) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SimulationRun_Job) GetUsage() *SimulationRun_Job_Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type SimulationRun_Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_Create) Reset() {
	*x = SimulationRun_Create{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Create) ProtoMessage() {}

func (x *SimulationRun_Create) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Create.ProtoReflect.Descriptor instead.
func (*SimulationRun_Create) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 1}
}

type SimulationRun_ConfirmSourceUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_ConfirmSourceUpload) Reset() {
	*x = SimulationRun_ConfirmSourceUpload{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_ConfirmSourceUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_ConfirmSourceUpload) ProtoMessage() {}

func (x *SimulationRun_ConfirmSourceUpload) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_ConfirmSourceUpload.ProtoReflect.Descriptor instead.
func (*SimulationRun_ConfirmSourceUpload) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 2}
}

type SimulationRun_Get struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_Get) Reset() {
	*x = SimulationRun_Get{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Get) ProtoMessage() {}

func (x *SimulationRun_Get) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Get.ProtoReflect.Descriptor instead.
func (*SimulationRun_Get) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 3}
}

type SimulationRun_List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_List) Reset() {
	*x = SimulationRun_List{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_List) ProtoMessage() {}

func (x *SimulationRun_List) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_List.ProtoReflect.Descriptor instead.
func (*SimulationRun_List) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 4}
}

type SimulationRun_Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_Cancel) Reset() {
	*x = SimulationRun_Cancel{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Cancel) ProtoMessage() {}

func (x *SimulationRun_Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Cancel.ProtoReflect.Descriptor instead.
func (*SimulationRun_Cancel) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 5}
}

type SimulationRun_Usage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TextTurnsCount  int32                  `protobuf:"varint,1,opt,name=text_turns_count,json=textTurnsCount,proto3" json:"text_turns_count,omitempty"`
	AudioTurnsCount int32                  `protobuf:"varint,2,opt,name=audio_turns_count,json=audioTurnsCount,proto3" json:"audio_turns_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulationRun_Usage) Reset() {
	*x = SimulationRun_Usage{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Usage) ProtoMessage() {}

func (x *SimulationRun_Usage) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Usage.ProtoReflect.Descriptor instead.
func (*SimulationRun_Usage) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 6}
}

func (x *SimulationRun_Usage) GetTextTurnsCount() int32 {
	if x != nil {
		return x.TextTurnsCount
	}
	return 0
}

func (x *SimulationRun_Usage) GetAudioTurnsCount() int32 {
	if x != nil {
		return x.AudioTurnsCount
	}
	return 0
}

type SimulationRun_Job_Usage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TextTurnsCount  int32                  `protobuf:"varint,1,opt,name=text_turns_count,json=textTurnsCount,proto3" json:"text_turns_count,omitempty"`
	AudioTurnsCount int32                  `protobuf:"varint,2,opt,name=audio_turns_count,json=audioTurnsCount,proto3" json:"audio_turns_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulationRun_Job_Usage) Reset() {
	*x = SimulationRun_Job_Usage{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Job_Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Job_Usage) ProtoMessage() {}

func (x *SimulationRun_Job_Usage) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Job_Usage.ProtoReflect.Descriptor instead.
func (*SimulationRun_Job_Usage) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *SimulationRun_Job_Usage) GetTextTurnsCount() int32 {
	if x != nil {
		return x.TextTurnsCount
	}
	return 0
}

func (x *SimulationRun_Job_Usage) GetAudioTurnsCount() int32 {
	if x != nil {
		return x.AudioTurnsCount
	}
	return 0
}

type SimulationRun_Create_Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AgentName      string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	NumSimulations int32                  `protobuf:"varint,4,opt,name=num_simulations,json=numSimulations,proto3" json:"num_simulations,omitempty"`
	Region         string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	// When set, run these scenarios (loaded from a scenarios.yaml).
	// When unset, generate num_simulations scenarios from the uploaded agent source.
	ScenarioGroup *ScenarioGroup `protobuf:"bytes,7,opt,name=scenario_group,json=scenarioGroup,proto3,oneof" json:"scenario_group,omitempty"`
	// Maximum simulate jobs running in parallel for this run. Clamped to the
	// project's concurrency quota; 0/unset uses the server default.
	Concurrency   *int32 `protobuf:"varint,8,opt,name=concurrency,proto3,oneof" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_Create_Request) Reset() {
	*x = SimulationRun_Create_Request{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Create_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Create_Request) ProtoMessage() {}

func (x *SimulationRun_Create_Request) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Create_Request.ProtoReflect.Descriptor instead.
func (*SimulationRun_Create_Request) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *SimulationRun_Create_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SimulationRun_Create_Request) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *SimulationRun_Create_Request) GetNumSimulations() int32 {
	if x != nil {
		return x.NumSimulations
	}
	return 0
}

func (x *SimulationRun_Create_Request) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SimulationRun_Create_Request) GetScenarioGroup() *ScenarioGroup {
	if x != nil {
		return x.ScenarioGroup
	}
	return nil
}

func (x *SimulationRun_Create_Request) GetConcurrency() int32 {
	if x != nil && x.Concurrency != nil {
		return *x.Concurrency
	}
	return 0
}

type SimulationRun_Create_Response struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SimulationRunId      string                 `protobuf:"bytes,1,opt,name=simulation_run_id,json=simulationRunId,proto3" json:"simulation_run_id,omitempty"`
	PresignedPostRequest *PresignedPostRequest  `protobuf:"bytes,2,opt,name=presigned_post_request,json=presignedPostRequest,proto3" json:"presigned_post_request,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SimulationRun_Create_Response) Reset() {
	*x = SimulationRun_Create_Response{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Create_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Create_Response) ProtoMessage() {}

func (x *SimulationRun_Create_Response) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Create_Response.ProtoReflect.Descriptor instead.
func (*SimulationRun_Create_Response) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 1, 1}
}

func (x *SimulationRun_Create_Response) GetSimulationRunId() string {
	if x != nil {
		return x.SimulationRunId
	}
	return ""
}

func (x *SimulationRun_Create_Response) GetPresignedPostRequest() *PresignedPostRequest {
	if x != nil {
		return x.PresignedPostRequest
	}
	return nil
}

type SimulationRun_ConfirmSourceUpload_Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SimulationRunId string                 `protobuf:"bytes,2,opt,name=simulation_run_id,json=simulationRunId,proto3" json:"simulation_run_id,omitempty"`
	CodeEntrypoint  string                 `protobuf:"bytes,3,opt,name=code_entrypoint,json=codeEntrypoint,proto3" json:"code_entrypoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulationRun_ConfirmSourceUpload_Request) Reset() {
	*x = SimulationRun_ConfirmSourceUpload_Request{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_ConfirmSourceUpload_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_ConfirmSourceUpload_Request) ProtoMessage() {}

func (x *SimulationRun_ConfirmSourceUpload_Request) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_ConfirmSourceUpload_Request.ProtoReflect.Descriptor instead.
func (*SimulationRun_ConfirmSourceUpload_Request) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 2, 0}
}

func (x *SimulationRun_ConfirmSourceUpload_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SimulationRun_ConfirmSourceUpload_Request) GetSimulationRunId() string {
	if x != nil {
		return x.SimulationRunId
	}
	return ""
}

func (x *SimulationRun_ConfirmSourceUpload_Request) GetCodeEntrypoint() string {
	if x != nil {
		return x.CodeEntrypoint
	}
	return ""
}

type SimulationRun_ConfirmSourceUpload_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_ConfirmSourceUpload_Response) Reset() {
	*x = SimulationRun_ConfirmSourceUpload_Response{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_ConfirmSourceUpload_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_ConfirmSourceUpload_Response) ProtoMessage() {}

func (x *SimulationRun_ConfirmSourceUpload_Response) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_ConfirmSourceUpload_Response.ProtoReflect.Descriptor instead.
func (*SimulationRun_ConfirmSourceUpload_Response) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 2, 1}
}

type SimulationRun_Get_Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SimulationRunId string                 `protobuf:"bytes,2,opt,name=simulation_run_id,json=simulationRunId,proto3" json:"simulation_run_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulationRun_Get_Request) Reset() {
	*x = SimulationRun_Get_Request{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Get_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Get_Request) ProtoMessage() {}

func (x *SimulationRun_Get_Request) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Get_Request.ProtoReflect.Descriptor instead.
func (*SimulationRun_Get_Request) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 3, 0}
}

func (x *SimulationRun_Get_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SimulationRun_Get_Request) GetSimulationRunId() string {
	if x != nil {
		return x.SimulationRunId
	}
	return ""
}

type SimulationRun_Get_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *SimulationRun         `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_Get_Response) Reset() {
	*x = SimulationRun_Get_Response{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Get_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Get_Response) ProtoMessage() {}

func (x *SimulationRun_Get_Response) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Get_Response.ProtoReflect.Descriptor instead.
func (*SimulationRun_Get_Response) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 3, 1}
}

func (x *SimulationRun_Get_Response) GetRun() *SimulationRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type SimulationRun_List_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        *SimulationRun_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=livekit.SimulationRun_Status,oneof" json:"status,omitempty"`
	PageToken     *TokenPagination       `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_List_Request) Reset() {
	*x = SimulationRun_List_Request{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_List_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_List_Request) ProtoMessage() {}

func (x *SimulationRun_List_Request) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_List_Request.ProtoReflect.Descriptor instead.
func (*SimulationRun_List_Request) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 4, 0}
}

func (x *SimulationRun_List_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SimulationRun_List_Request) GetStatus() SimulationRun_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return SimulationRun_STATUS_PENDING_UPLOAD
}

func (x *SimulationRun_List_Request) GetPageToken() *TokenPagination {
	if x != nil {
		return x.PageToken
	}
	return nil
}

type SimulationRun_List_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*SimulationRun       `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken *TokenPagination       `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_List_Response) Reset() {
	*x = SimulationRun_List_Response{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_List_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_List_Response) ProtoMessage() {}

func (x *SimulationRun_List_Response) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_List_Response.ProtoReflect.Descriptor instead.
func (*SimulationRun_List_Response) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 4, 1}
}

func (x *SimulationRun_List_Response) GetRuns() []*SimulationRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *SimulationRun_List_Response) GetNextPageToken() *TokenPagination {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

type SimulationRun_Cancel_Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SimulationRunId string                 `protobuf:"bytes,2,opt,name=simulation_run_id,json=simulationRunId,proto3" json:"simulation_run_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulationRun_Cancel_Request) Reset() {
	*x = SimulationRun_Cancel_Request{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Cancel_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Cancel_Request) ProtoMessage() {}

func (x *SimulationRun_Cancel_Request) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Cancel_Request.ProtoReflect.Descriptor instead.
func (*SimulationRun_Cancel_Request) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 5, 0}
}

func (x *SimulationRun_Cancel_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SimulationRun_Cancel_Request) GetSimulationRunId() string {
	if x != nil {
		return x.SimulationRunId
	}
	return ""
}

type SimulationRun_Cancel_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRun_Cancel_Response) Reset() {
	*x = SimulationRun_Cancel_Response{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRun_Cancel_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRun_Cancel_Response) ProtoMessage() {}

func (x *SimulationRun_Cancel_Response) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRun_Cancel_Response.ProtoReflect.Descriptor instead.
func (*SimulationRun_Cancel_Response) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{1, 5, 1}
}

type Scenario_CreateFromSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario_CreateFromSession) Reset() {
	*x = Scenario_CreateFromSession{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario_CreateFromSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario_CreateFromSession) ProtoMessage() {}

func (x *Scenario_CreateFromSession) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario_CreateFromSession.ProtoReflect.Descriptor instead.
func (*Scenario_CreateFromSession) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{2, 0}
}

type Scenario_CreateFromSession_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario_CreateFromSession_Request) Reset() {
	*x = Scenario_CreateFromSession_Request{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario_CreateFromSession_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario_CreateFromSession_Request) ProtoMessage() {}

func (x *Scenario_CreateFromSession_Request) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario_CreateFromSession_Request.ProtoReflect.Descriptor instead.
func (*Scenario_CreateFromSession_Request) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Scenario_CreateFromSession_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Scenario_CreateFromSession_Request) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Scenario_CreateFromSession_Request) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type Scenario_CreateFromSession_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *Scenario              `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario_CreateFromSession_Response) Reset() {
	*x = Scenario_CreateFromSession_Response{}
	mi := &file_livekit_agent_simulation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario_CreateFromSession_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario_CreateFromSession_Response) ProtoMessage() {}

func (x *Scenario_CreateFromSession_Response) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_agent_simulation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario_CreateFromSession_Response.ProtoReflect.Descriptor instead.
func (*Scenario_CreateFromSession_Response) Descriptor() ([]byte, []int) {
	return file_livekit_agent_simulation_proto_rawDescGZIP(), []int{2, 0, 1}
}

func (x *Scenario_CreateFromSession_Response) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

var File_livekit_agent_simulation_proto protoreflect.FileDescriptor

const file_livekit_agent_simulation_proto_rawDesc = "" +
	"\n" +
	"\x1elivekit_agent_simulation.proto\x12\alivekit\x1a!agent/livekit_agent_session.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19livekit_cloud_agent.proto\x1a\x14livekit_models.proto\"\xd1\x03\n" +
	"\x14SimulationRunSummary\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\x05R\x06passed\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x1d\n" +
	"\n" +
	"going_well\x18\x03 \x01(\tR\tgoingWell\x12\x1d\n" +
	"\n" +
	"to_improve\x18\x04 \x01(\tR\ttoImprove\x12;\n" +
	"\x06issues\x18\x05 \x03(\v2#.livekit.SimulationRunSummary.IssueR\x06issues\x12Q\n" +
	"\fchat_history\x18\x06 \x03(\v2..livekit.SimulationRunSummary.ChatHistoryEntryR\vchatHistory\x1aZ\n" +
	"\x10ChatHistoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.livekit.agent.ChatContextR\x05value:\x028\x01\x1a_\n" +
	"\x05Issue\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x02 \x01(\tR\n" +
	"suggestion\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\x9f\x16\n" +
	"\rSimulationRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.livekit.SimulationRun.StatusR\x06status\x12+\n" +
	"\x11agent_description\x18\x04 \x01(\tR\x10agentDescription\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12.\n" +
	"\x04jobs\x18\a \x03(\v2\x1a.livekit.SimulationRun.JobR\x04jobs\x12\x1d\n" +
	"\n" +
	"agent_name\x18\t \x01(\tR\tagentName\x12=\n" +
	"\x0escenario_group\x18\n" +
	" \x01(\v2\x16.livekit.ScenarioGroupR\rscenarioGroup\x125\n" +
	"\bended_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x1b\n" +
	"\tjob_count\x18\f \x01(\x05R\bjobCount\x12!\n" +
	"\fpassed_count\x18\r \x01(\x05R\vpassedCount\x12!\n" +
	"\ffailed_count\x18\x0e \x01(\x05R\vfailedCount\x12'\n" +
	"\x0fnum_simulations\x18\x0f \x01(\x05R\x0enumSimulations\x122\n" +
	"\x05usage\x18\x10 \x01(\v2\x1c.livekit.SimulationRun.UsageR\x05usage\x12 \n" +
	"\vconcurrency\x18\x11 \x01(\x05R\vconcurrency\x12!\n" +
	"\fsummary_zstd\x18\x12 \x01(\fR\vsummaryZstd\x1a\x99\x05\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.livekit.SimulationRun.Job.StatusR\x06status\x12\"\n" +
	"\finstructions\x18\x03 \x01(\tR\finstructions\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12-\n" +
	"\x12agent_expectations\x18\x05 \x01(\tR\x11agentExpectations\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1b\n" +
	"\troom_name\x18\b \x01(\tR\broomName\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x17\n" +
	"\aroom_id\x18\f \x01(\tR\x06roomId\x126\n" +
	"\x05usage\x18\r \x01(\v2 .livekit.SimulationRun.Job.UsageR\x05usage\x1a]\n" +
	"\x05Usage\x12(\n" +
	"\x10text_turns_count\x18\x01 \x01(\x05R\x0etextTurnsCount\x12*\n" +
	"\x11audio_turns_count\x18\x02 \x01(\x05R\x0faudioTurnsCount\"o\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x00\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x01\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x04J\x04\b\t\x10\n" +
	"\x1a\xc8\x03\n" +
	"\x06Create\x1a\xaf\x02\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12'\n" +
	"\x0fnum_simulations\x18\x04 \x01(\x05R\x0enumSimulations\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12B\n" +
	"\x0escenario_group\x18\a \x01(\v2\x16.livekit.ScenarioGroupH\x00R\rscenarioGroup\x88\x01\x01\x12%\n" +
	"\vconcurrency\x18\b \x01(\x05H\x01R\vconcurrency\x88\x01\x01B\x11\n" +
	"\x0f_scenario_groupB\x0e\n" +
	"\f_concurrencyJ\x04\b\x03\x10\x04R\x11agent_description\x1a\x8b\x01\n" +
	"\bResponse\x12*\n" +
	"\x11simulation_run_id\x18\x01 \x01(\tR\x0fsimulationRunId\x12S\n" +
	"\x16presigned_post_request\x18\x02 \x01(\v2\x1d.livekit.PresignedPostRequestR\x14presignedPostRequest\x1a\xa0\x01\n" +
	"\x13ConfirmSourceUpload\x1a}\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12*\n" +
	"\x11simulation_run_id\x18\x02 \x01(\tR\x0fsimulationRunId\x12'\n" +
	"\x0fcode_entrypoint\x18\x03 \x01(\tR\x0ecodeEntrypoint\x1a\n" +
	"\n" +
	"\bResponse\x1a\x91\x01\n" +
	"\x03Get\x1aT\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12*\n" +
	"\x11simulation_run_id\x18\x02 \x01(\tR\x0fsimulationRunId\x1a4\n" +
	"\bResponse\x12(\n" +
	"\x03run\x18\x01 \x01(\v2\x16.livekit.SimulationRunR\x03run\x1a\xbf\x02\n" +
	"\x04List\x1a\xbc\x01\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.livekit.SimulationRun.StatusH\x00R\x06status\x88\x01\x01\x12<\n" +
	"\n" +
	"page_token\x18\x03 \x01(\v2\x18.livekit.TokenPaginationH\x01R\tpageToken\x88\x01\x01B\t\n" +
	"\a_statusB\r\n" +
	"\v_page_token\x1ax\n" +
	"\bResponse\x12*\n" +
	"\x04runs\x18\x01 \x03(\v2\x16.livekit.SimulationRunR\x04runs\x12@\n" +
	"\x0fnext_page_token\x18\x02 \x01(\v2\x18.livekit.TokenPaginationR\rnextPageToken\x1aj\n" +
	"\x06Cancel\x1aT\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12*\n" +
	"\x11simulation_run_id\x18\x02 \x01(\tR\x0fsimulationRunId\x1a\n" +
	"\n" +
	"\bResponse\x1a]\n" +
	"\x05Usage\x12(\n" +
	"\x10text_turns_count\x18\x01 \x01(\x05R\x0etextTurnsCount\x12*\n" +
	"\x11audio_turns_count\x18\x02 \x01(\x05R\x0faudioTurnsCount\"\xa5\x01\n" +
	"\x06Status\x12\x19\n" +
	"\x15STATUS_PENDING_UPLOAD\x10\x00\x12\x15\n" +
	"\x11STATUS_GENERATING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x16\n" +
	"\x12STATUS_SUMMARIZING\x10\x03\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x04\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x05\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x06J\x04\b\b\x10\tR\asummary\"\xa5\x03\n" +
	"\bScenario\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\"\n" +
	"\finstructions\x18\x02 \x01(\tR\finstructions\x12-\n" +
	"\x12agent_expectations\x18\x03 \x01(\tR\x11agentExpectations\x12/\n" +
	"\x04tags\x18\x04 \x03(\v2\x1b.livekit.Scenario.TagsEntryR\x04tags\x12\x1a\n" +
	"\buserdata\x18\x05 \x01(\tR\buserdata\x1a\xa9\x01\n" +
	"\x11CreateFromSession\x1aY\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x1a9\n" +
	"\bResponse\x12-\n" +
	"\bscenario\x18\x01 \x01(\v2\x11.livekit.ScenarioR\bscenario\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\rScenarioGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\tscenarios\x18\x02 \x03(\v2\x11.livekit.ScenarioR\tscenarios\"\xb3\x01\n" +
	"\x12SimulationDispatch\x12*\n" +
	"\x11simulation_run_id\x18\x01 \x01(\tR\x0fsimulationRunId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12-\n" +
	"\bscenario\x18\x03 \x01(\v2\x11.livekit.ScenarioR\bscenario\x12+\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x17.livekit.SimulationModeR\x04mode*f\n" +
	"\x0eSimulationMode\x12\x1f\n" +
	"\x1bSIMULATION_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SIMULATION_MODE_TEXT\x10\x01\x12\x19\n" +
	"\x15SIMULATION_MODE_AUDIO\x10\x022\x9e\x05\n" +
	"\x0fAgentSimulation\x12d\n" +
	"\x13CreateSimulationRun\x12%.livekit.SimulationRun.Create.Request\x1a&.livekit.SimulationRun.Create.Response\x12\x88\x01\n" +
	"\x1dConfirmSimulationSourceUpload\x122.livekit.SimulationRun.ConfirmSourceUpload.Request\x1a3.livekit.SimulationRun.ConfirmSourceUpload.Response\x12[\n" +
	"\x10GetSimulationRun\x12\".livekit.SimulationRun.Get.Request\x1a#.livekit.SimulationRun.Get.Response\x12_\n" +
	"\x12ListSimulationRuns\x12#.livekit.SimulationRun.List.Request\x1a$.livekit.SimulationRun.List.Response\x12d\n" +
	"\x13CancelSimulationRun\x12%.livekit.SimulationRun.Cancel.Request\x1a&.livekit.SimulationRun.Cancel.Response\x12v\n" +
	"\x19CreateScenarioFromSession\x12+.livekit.Scenario.CreateFromSession.Request\x1a,.livekit.Scenario.CreateFromSession.ResponseBFZ#github.com/livekit/protocol/livekit\xaa\x02\rLiveKit.Proto\xea\x02\x0eLiveKit::Protob\x06proto3"

var (
	file_livekit_agent_simulation_proto_rawDescOnce sync.Once
	file_livekit_agent_simulation_proto_rawDescData []byte
)

func file_livekit_agent_simulation_proto_rawDescGZIP() []byte {
	file_livekit_agent_simulation_proto_rawDescOnce.Do(func() {
		file_livekit_agent_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livekit_agent_simulation_proto_rawDesc), len(file_livekit_agent_simulation_proto_rawDesc)))
	})
	return file_livekit_agent_simulation_proto_rawDescData
}

var file_livekit_agent_simulation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_livekit_agent_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_livekit_agent_simulation_proto_goTypes = []any{
	(SimulationMode)(0),                                // 0: livekit.SimulationMode
	(SimulationRun_Status)(0),                          // 1: livekit.SimulationRun.Status
	(SimulationRun_Job_Status)(0),                      // 2: livekit.SimulationRun.Job.Status
	(*SimulationRunSummary)(nil),                       // 3: livekit.SimulationRunSummary
	(*SimulationRun)(nil),                              // 4: livekit.SimulationRun
	(*Scenario)(nil),                                   // 5: livekit.Scenario
	(*ScenarioGroup)(nil),                              // 6: livekit.ScenarioGroup
	(*SimulationDispatch)(nil),                         // 7: livekit.SimulationDispatch
	nil,                                                // 8: livekit.SimulationRunSummary.ChatHistoryEntry
	(*SimulationRunSummary_Issue)(nil),                 // 9: livekit.SimulationRunSummary.Issue
	(*SimulationRun_Job)(nil),                          // 10: livekit.SimulationRun.Job
	(*SimulationRun_Create)(nil),                       // 11: livekit.SimulationRun.Create
	(*SimulationRun_ConfirmSourceUpload)(nil),          // 12: livekit.SimulationRun.ConfirmSourceUpload
	(*SimulationRun_Get)(nil),                          // 13: livekit.SimulationRun.Get
	(*SimulationRun_List)(nil),                         // 14: livekit.SimulationRun.List
	(*SimulationRun_Cancel)(nil),                       // 15: livekit.SimulationRun.Cancel
	(*SimulationRun_Usage)(nil),                        // 16: livekit.SimulationRun.Usage
	(*SimulationRun_Job_Usage)(nil),                    // 17: livekit.SimulationRun.Job.Usage
	(*SimulationRun_Create_Request)(nil),               // 18: livekit.SimulationRun.Create.Request
	(*SimulationRun_Create_Response)(nil),              // 19: livekit.SimulationRun.Create.Response
	(*SimulationRun_ConfirmSourceUpload_Request)(nil),  // 20: livekit.SimulationRun.ConfirmSourceUpload.Request
	(*SimulationRun_ConfirmSourceUpload_Response)(nil), // 21: livekit.SimulationRun.ConfirmSourceUpload.Response
	(*SimulationRun_Get_Request)(nil),                  // 22: livekit.SimulationRun.Get.Request
	(*SimulationRun_Get_Response)(nil),                 // 23: livekit.SimulationRun.Get.Response
	(*SimulationRun_List_Request)(nil),                 // 24: livekit.SimulationRun.List.Request
	(*SimulationRun_List_Response)(nil),                // 25: livekit.SimulationRun.List.Response
	(*SimulationRun_Cancel_Request)(nil),               // 26: livekit.SimulationRun.Cancel.Request
	(*SimulationRun_Cancel_Response)(nil),              // 27: livekit.SimulationRun.Cancel.Response
	(*Scenario_CreateFromSession)(nil),                 // 28: livekit.Scenario.CreateFromSession
	nil,                                                // 29: livekit.Scenario.TagsEntry
	(*Scenario_CreateFromSession_Request)(nil),         // 30: livekit.Scenario.CreateFromSession.Request
	(*Scenario_CreateFromSession_Response)(nil),        // 31: livekit.Scenario.CreateFromSession.Response
	(*timestamppb.Timestamp)(nil),                      // 32: google.protobuf.Timestamp
	(*agent.ChatContext)(nil),                          // 33: livekit.agent.ChatContext
	(*PresignedPostRequest)(nil),                       // 34: livekit.PresignedPostRequest
	(*TokenPagination)(nil),                            // 35: livekit.TokenPagination
}
var file_livekit_agent_simulation_proto_depIdxs = []int32{
	9,  // 0: livekit.SimulationRunSummary.issues:type_name -> livekit.SimulationRunSummary.Issue
	8,  // 1: livekit.SimulationRunSummary.chat_history:type_name -> livekit.SimulationRunSummary.ChatHistoryEntry
	1,  // 2: livekit.SimulationRun.status:type_name -> livekit.SimulationRun.Status
	32, // 3: livekit.SimulationRun.created_at:type_name -> google.protobuf.Timestamp
	10, // 4: livekit.SimulationRun.jobs:type_name -> livekit.SimulationRun.Job
	6,  // 5: livekit.SimulationRun.scenario_group:type_name -> livekit.ScenarioGroup
	32, // 6: livekit.SimulationRun.ended_at:type_name -> google.protobuf.Timestamp
	16, // 7: livekit.SimulationRun.usage:type_name -> livekit.SimulationRun.Usage
	29, // 8: livekit.Scenario.tags:type_name -> livekit.Scenario.TagsEntry
	5,  // 9: livekit.ScenarioGroup.scenarios:type_name -> livekit.Scenario
	5,  // 10: livekit.SimulationDispatch.scenario:type_name -> livekit.Scenario
	0,  // 11: livekit.SimulationDispatch.mode:type_name -> livekit.SimulationMode
	33, // 12: livekit.SimulationRunSummary.ChatHistoryEntry.value:type_name -> livekit.agent.ChatContext
	2,  // 13: livekit.SimulationRun.Job.status:type_name -> livekit.SimulationRun.Job.Status
	32, // 14: livekit.SimulationRun.Job.started_at:type_name -> google.protobuf.Timestamp
	32, // 15: livekit.SimulationRun.Job.ended_at:type_name -> google.protobuf.Timestamp
	17, // 16: livekit.SimulationRun.Job.usage:type_name -> livekit.SimulationRun.Job.Usage
	6,  // 17: livekit.SimulationRun.Create.Request.scenario_group:type_name -> livekit.ScenarioGroup
	34, // 18: livekit.SimulationRun.Create.Response.presigned_post_request:type_name -> livekit.PresignedPostRequest
	4,  // 19: livekit.SimulationRun.Get.Response.run:type_name -> livekit.SimulationRun
	1,  // 20: livekit.SimulationRun.List.Request.status:type_name -> livekit.SimulationRun.Status
	35, // 21: livekit.SimulationRun.List.Request.page_token:type_name -> livekit.TokenPagination
	4,  // 22: livekit.SimulationRun.List.Response.runs:type_name -> livekit.SimulationRun
	35, // 23: livekit.SimulationRun.List.Response.next_page_token:type_name -> livekit.TokenPagination
	5,  // 24: livekit.Scenario.CreateFromSession.Response.scenario:type_name -> livekit.Scenario
	18, // 25: livekit.AgentSimulation.CreateSimulationRun:input_type -> livekit.SimulationRun.Create.Request
	20, // 26: livekit.AgentSimulation.ConfirmSimulationSourceUpload:input_type -> livekit.SimulationRun.ConfirmSourceUpload.Request
	22, // 27: livekit.AgentSimulation.GetSimulationRun:input_type -> livekit.SimulationRun.Get.Request
	24, // 28: livekit.AgentSimulation.ListSimulationRuns:input_type -> livekit.SimulationRun.List.Request
	26, // 29: livekit.AgentSimulation.CancelSimulationRun:input_type -> livekit.SimulationRun.Cancel.Request
	30, // 30: livekit.AgentSimulation.CreateScenarioFromSession:input_type -> livekit.Scenario.CreateFromSession.Request
	19, // 31: livekit.AgentSimulation.CreateSimulationRun:output_type -> livekit.SimulationRun.Create.Response
	21, // 32: livekit.AgentSimulation.ConfirmSimulationSourceUpload:output_type -> livekit.SimulationRun.ConfirmSourceUpload.Response
	23, // 33: livekit.AgentSimulation.GetSimulationRun:output_type -> livekit.SimulationRun.Get.Response
	25, // 34: livekit.AgentSimulation.ListSimulationRuns:output_type -> livekit.SimulationRun.List.Response
	27, // 35: livekit.AgentSimulation.CancelSimulationRun:output_type -> livekit.SimulationRun.Cancel.Response
	31, // 36: livekit.AgentSimulation.CreateScenarioFromSession:output_type -> livekit.Scenario.CreateFromSession.Response
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_livekit_agent_simulation_proto_init() }
func file_livekit_agent_simulation_proto_init() {
	if File_livekit_agent_simulation_proto != nil {
		return
	}
	file_livekit_cloud_agent_proto_init()
	file_livekit_models_proto_init()
	file_livekit_agent_simulation_proto_msgTypes[15].OneofWrappers = []any{}
	file_livekit_agent_simulation_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livekit_agent_simulation_proto_rawDesc), len(file_livekit_agent_simulation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livekit_agent_simulation_proto_goTypes,
		DependencyIndexes: file_livekit_agent_simulation_proto_depIdxs,
		EnumInfos:         file_livekit_agent_simulation_proto_enumTypes,
		MessageInfos:      file_livekit_agent_simulation_proto_msgTypes,
	}.Build()
	File_livekit_agent_simulation_proto = out.File
	file_livekit_agent_simulation_proto_goTypes = nil
	file_livekit_agent_simulation_proto_depIdxs = nil
}
